// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Since 1956, Simbalion has been leaving a vibrant mark on Taiwan. From childhood crayons to our iconic, generation-spanning permanent markers, we consistently break the mold. In 2020, we established th",
    "brand.summary": "Since 1956, Simbalion has been leaving a vibrant mark on Taiwan. From childhood crayons to our iconic, generation-spanning permanent markers, we consistently break the mold. In 2020, we established the \"Imagination Factory,\" an interactive art museum, to drive cross-generational creative experimentation and aesthetic exploration. We invite you to join us and ignite your imagination!",
    "brand.product1.name": "Fuits And Vegetables",
    "brand.product1.desc": "The right gift means more than an expensive one! A foolproof and incredibly fun choice for gifting:\nIt's not just a crayon—it's a building block! Letting imagination go beyond the paper.\nCrafted from natural rice bran oil and 100% paraffin-free. Carefully handmade, meaning every single piece is completely unique!\nPlus, the mess-free design lets you scribble and color to your heart's content without worrying about dirty hands!",
    "brand.product2.name": "Popsicle Gradient Rice crayon",
    "brand.product2.desc": "Summer delights that never melt—feast your eyes on a popsicle! Draw in gorgeous gradients where every stroke brings a sweet surprise. Carefully handcrafted, making the color blend of every single piece completely one-of-a-kind. Made from natural rice bran and 100% paraffin-free, they are safe, non-toxic, and deliver highly vibrant colors. Plus, the mess-free design ensures a comfortable grip for effortless coloring!",
    "brand.product3.name": "KREEMO quiet stationary set",
    "brand.product3.desc": "The \"Inobtrusive Stationery\" Series: Minimalist design at its core, reducing visual noise to create more space for focus.\n\nThis exhibition's featured collection is identified by its pale green eco-friendly materials, transforming sustainability into quiet, refreshing everyday tools. The tape dispenser is crafted from recycled plastics, bringing repurposed materials back to your workspace. Meanwhile, our markers feature a refillable design to extend their lifespan and minimize single-use waste.\n\nFrom materials and colors to the way they function, the \"Inobtrusive\" series never seeks the spotlight. Instead, with every use, it quietly practices a kinder choice for our world."
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "雄獅文具跨越 70 載 美學創意的領先驅動者",
    "brand.summary": "雄獅文具跨越 70 載 美學創意的領先驅動者\n自 1959 年起，雄獅文具打造出台灣的色彩印記。從學齡蠟筆到跨世代奇異筆，我們持續跳脫框架，更創立「想像力製造所」美學館，將研發底蘊轉化為沈浸式藝術體驗，驅動跨世代的創意實驗與美學探索，邀您一同激發想像力！",
    "brand.product1.name": "頂級水果禮盒(米蠟筆組)",
    "brand.product1.desc": "送對東西比送貴東西重要，不敗的選項，送禮更有趣的選擇，不只是蠟筆還能是積木，讓想像力突破紙張，天然米糠油製作，不含石蠟，手工製作，每一塊都不一樣!?不沾手設計，塗塗抹抹不怕手髒亂亂抹!!",
    "brand.product2.name": "枝仔冰(漸層米蠟筆)",
    "brand.product2.desc": "融不掉的夏日美好，讓你用眼睛吃冰棒！畫出漸變色，每一筆都是驚喜，手工製作，每一枝的漸層都是獨一無二，天然米糠製成不含石蠟，安全無毒顯色性佳，不沾手設計，手握更好塗!",
    "brand.product3.name": "Kreemo 不打擾文具組",
    "brand.product3.desc": "不打擾文具系列，以極簡留白為設計核心，讓桌面少一點視覺噪音，多一點專注空間。\n\n本次參展版本以淡綠色環保材質作為識別，將永續概念轉化為安靜、清爽的日常文具。系列中，膠帶台預計採用回收塑料製造，讓被重新利用的材料回到桌面；辨識筆則以可補充墨水設計延長使用壽命，減少一次性耗材的浪費。\n\n從材質、色彩到使用方式，不打擾文具系列不刻意張揚，卻在每一次使用中，悄悄實踐更友善的選擇。"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Simbalion laat al zijn levendige stempel achter op Taiwan. Van kinderkrijt tot onze iconische, generatieoverstijgende permanente markers, doorbreken wij consequent de mal.",
    "brand.summary": "Simbalion laat al zijn levendige stempel achter op Taiwan. Van kinderkrijt tot onze iconische, generatieoverstijgende permanente markers, doorbreken wij consequent de mal. In 2020 richtten we de \u201cImagination Factory\u201d op, een interactief kunstmuseum, om generatieoverstijgende creatieve experimenten en esthetische verkenning te stimuleren. Wij nodigen u uit om samen met ons uw verbeelding aan te wakkeren!",
    "brand.product1.name": "Fuits And Vegetables",
    "brand.product1.desc": "The right gift means more than an expensive one! A foolproof and incredibly fun choice for gifting:\nIt's not just a crayon—it's a building block! Letting imagination go beyond the paper.\nCrafted from natural rice bran oil and 100% paraffin-free. Carefully handmade, meaning every single piece is completely unique!\nPlus, the mess-free design lets you scribble and color to your heart's content without worrying about dirty hands!",
    "brand.product2.name": "Popsicle Gradient Rice crayon",
    "brand.product2.desc": "Summer delights that never melt—feast your eyes on a popsicle! Draw in gorgeous gradients where every stroke brings a sweet surprise. Carefully handcrafted, making the color blend of every single piece completely one-of-a-kind. Made from natural rice bran and 100% paraffin-free, they are safe, non-toxic, and deliver highly vibrant colors. Plus, the mess-free design ensures a comfortable grip for effortless coloring!",
    "brand.product3.name": "KREEMO quiet stationary set",
    "brand.product3.desc": "The \"Inobtrusive Stationery\" Series: Minimalist design at its core, reducing visual noise to create more space for focus.\n\nThis exhibition's featured collection is identified by its pale green eco-friendly materials, transforming sustainability into quiet, refreshing everyday tools. The tape dispenser is crafted from recycled plastics, bringing repurposed materials back to your workspace. Meanwhile, our markers feature a refillable design to extend their lifespan and minimize single-use waste.\n\nFrom materials and colors to the way they function, the \"Inobtrusive\" series never seeks the spotlight. Instead, with every use, it quietly practices a kinder choice for our world."
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "1956\u5e74\u4ee5\u6765\u3001\u96c4\u7345\uff08Simbalion\uff09\u306f\u53f0\u6e7e\u306b\u9bae\u3084\u304b\u306a\u8db3\u8de1\u3092\u523a\u3057\u7d9a\u3051\u3066\u3044\u307e\u3059\u3002\u5b50\u4f9b\u306e\u9803\u306e\u30af\u30ec\u30e8\u30f3\u304b\u3089\u4e16\u4ee3\u3092\u8d85\u3048\u305f\u8c61\u5fb4\u7684\u306a\u6cb9\u6027\u30de\u30fc\u30ab\u30fc\u307e\u3067\u3001\u5e38\u8b58\u3092\u6253\u3061\u7834\u308a\u7d9a\u3051\u3066\u3044\u307e\u3059\u3002",
    "brand.summary": "1956\u5e74\u4ee5\u6765\u3001\u96c4\u7345\uff08Simbalion\uff09\u306f\u53f0\u6e7e\u306b\u9bae\u3084\u304b\u306a\u8db3\u8de1\u3092\u523a\u3057\u7d9a\u3051\u3066\u3044\u307e\u3059\u3002\u5b50\u4f9b\u306e\u9803\u306e\u30af\u30ec\u30e8\u30f3\u304b\u3089\u4e16\u4ee3\u3092\u8d85\u3048\u305f\u8c61\u5fb4\u7684\u306a\u6cb9\u6027\u30de\u30fc\u30ab\u30fc\u307e\u3067\u3001\u5e38\u8b58\u3092\u6253\u3061\u7834\u308a\u7d9a\u3051\u3066\u3044\u307e\u3059\u3002\n2020\u5e74\u306b\u306f\u300c\u60f3\u50cf\u529b\u5de5\u5834\uff08Imagination Factory\uff09\u300d\u3068\u3044\u3046\u30a4\u30f3\u30bf\u30e9\u30af\u30c6\u30a3\u30d6\u30a2\u30fc\u30c8\u30df\u30e5\u30fc\u30b8\u30a2\u30e0\u3092\u8a2d\u7acb\u3057\u3001\u4e16\u4ee3\u3092\u8d85\u3048\u305f\u5275\u9020\u7684\u306a\u5b9f\u9a13\u3068\u7f8e\u7684\u63a2\u6c42\u3092\u4fc3\u9032\u3057\u3066\u3044\u307e\u3059\u3002\u305c\u3072\u3054\u53c2\u52a0\u3044\u305f\u3060\u304d\u3001\u60f3\u50cf\u529b\u3092\u89e3\u304d\u653e\u3061\u307e\u3057\u3087\u3046\uff01",
    "brand.product1.name": "Fuits And Vegetables",
    "brand.product1.desc": "The right gift means more than an expensive one! A foolproof and incredibly fun choice for gifting:\nIt's not just a crayon—it's a building block! Letting imagination go beyond the paper.\nCrafted from natural rice bran oil and 100% paraffin-free. Carefully handmade, meaning every single piece is completely unique!\nPlus, the mess-free design lets you scribble and color to your heart's content without worrying about dirty hands!",
    "brand.product2.name": "Popsicle Gradient Rice crayon",
    "brand.product2.desc": "Summer delights that never melt—feast your eyes on a popsicle! Draw in gorgeous gradients where every stroke brings a sweet surprise. Carefully handcrafted, making the color blend of every single piece completely one-of-a-kind. Made from natural rice bran and 100% paraffin-free, they are safe, non-toxic, and deliver highly vibrant colors. Plus, the mess-free design ensures a comfortable grip for effortless coloring!",
    "brand.product3.name": "KREEMO quiet stationary set",
    "brand.product3.desc": "The \"Inobtrusive Stationery\" Series: Minimalist design at its core, reducing visual noise to create more space for focus.\n\nThis exhibition's featured collection is identified by its pale green eco-friendly materials, transforming sustainability into quiet, refreshing everyday tools. The tape dispenser is crafted from recycled plastics, bringing repurposed materials back to your workspace. Meanwhile, our markers feature a refillable design to extend their lifespan and minimize single-use waste.\n\nFrom materials and colors to the way they function, the \"Inobtrusive\" series never seeks the spotlight. Instead, with every use, it quietly practices a kinder choice for our world."
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w1000" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w1000" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "https://drive.google.com/thumbnail?id=1fu8za9qt7vSoVVp2eGyy3X6SGssJdNyW&sz=w1000" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "https://drive.google.com/thumbnail?id=1JSh9469-8TcrtswUQCt8lOnkcEpgiyrR&sz=w1000" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "https://drive.google.com/thumbnail?id=1lNf4a32YEWEf-X1HMMoUDBU06w1yr4pR&sz=w1000" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "https://drive.google.com/thumbnail?id=1J9nMzczqJ0qBV6YhNthCuxbEyN66pmPF&sz=w1000" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w1000" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w1000" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+ 優織隆企業股份有限公司", category: "SR MARK Brand", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "SR MARK Brand", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" },
  { name: "Yuantai 元泰竹藝社", category: "SR MARK Brand", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w1000" },
  { name: "Mr.Sci Science Factory 賽先生科學工廠", category: "SR MARK Brand", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" },
  { name: "GUTS STUDIO 有義器", category: "SR MARK Brand", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w1000" },
  { name: "ECOJOY", category: "SR MARK Brand", folder: "7-ECOJOY", image: "https://drive.google.com/thumbnail?id=1fu8za9qt7vSoVVp2eGyy3X6SGssJdNyW&sz=w1000" },
  { name: "JIAO 角琉璃", category: "SR MARK Brand", folder: "8-JIAO", image: "https://drive.google.com/thumbnail?id=1JSh9469-8TcrtswUQCt8lOnkcEpgiyrR&sz=w1000" },
  { name: "REWOOD Forest Cycle REWOOD森林循環", category: "SR MARK Brand", folder: "9-REWOOD", image: "https://drive.google.com/thumbnail?id=1lNf4a32YEWEf-X1HMMoUDBU06w1yr4pR&sz=w1000" },
  { name: "HongJi Box Art Co., Ltd 宏吉盒藝有限公司", category: "SR MARK Brand", folder: "10-HONGJI", image: "https://drive.google.com/thumbnail?id=1J9nMzczqJ0qBV6YhNthCuxbEyN66pmPF&sz=w1000" },
  { name: "Double Dribble 二次運球", category: "SR MARK Brand", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w1000" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
