// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "從事工業設計的設計師，因為熱愛手沖咖啡而向台灣烘豆冠軍老師學習了咖啡技術，",
    "brand.summary": "從事工業設計的設計師，因為熱愛手沖咖啡而向台灣烘豆冠軍老師學習了咖啡技術，\n2018年碰上了陶土，就此一頭栽進陶瓷傳統工藝的世界，越陷越深。\n\n有-「與人同者，物必歸焉，故受之以大有。」尋找到志同道合的人，大家齊心協力，就能大有斬獲。\n\n義-「義者，心之制、事之宜也。」義就是人內在的自我規範，顯現於外在就是待人處事合理與適當。\n\n器-「埏埴以為器，當其無，有器之用。」揉和陶土做成器皿，中空，才有器皿的功用。\n\n用最真誠的態度做高品質的精品陶瓷咖啡器皿，串起不同領域的你我，共享生活的美好，就是最有義器的樣子！\n\n",
    "brand.product1.name": "TURBO Coffee Dripper",
    "brand.product1.desc": "利用工業設計的背景，開發保留傳統工藝技術，但不失現代專業咖啡沖煮需求的MIT精品濾杯!\n",
    "brand.product2.name": "TURBO Sweet Coffee Dripper",
    "brand.product2.desc": "為了咖啡沖煮賽催生的新濾杯!\nTurbo Sweet維持原有特殊斜角設計的堅挺肋骨，\n深度0.5公分加速排氣，流速更順暢 ，\n新設計除了縮小尺寸，不同以往濾杯直通到底的肋骨，\n距離底部3公分處多了1公分長的截斷，\n呈現完美雙渦輪的意象，\n水流抵達截斷高度時，流速減緩，\n使粉水接觸時間增加20%，有利於沖煮時的甜感累積 !",
    "brand.product3.name": "Snow Red Aroma Preseving Cup",
    "brand.product3.desc": "以往喝咖啡香氣都會隨時間與溫度流失，但留香杯卻顛覆常識「越陳越香」，\n⠀\n極限縮口的設計，不只造型優雅，更能鎖住香氣分子，讓香氣不散、持續聚集，長時間讓香氣在杯內保留迴盪，不論是高溫、中溫或低溫，都極大化的讓咖啡香氣在每一口品嚐中刺激著嗅覺感官，透過外觀、結構還有釉色在視覺、味覺跟觸覺上讓圓潤飽滿的甜感加疊，一直到最後一口，都能滿足我們對手沖精品咖啡的追求！"
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "從事工業設計的設計師，因為熱愛手沖咖啡而向台灣烘豆冠軍老師學習了咖啡技術，",
    "brand.summary": "從事工業設計的設計師，因為熱愛手沖咖啡而向台灣烘豆冠軍老師學習了咖啡技術，\n2018年碰上了陶土，就此一頭栽進陶瓷傳統工藝的世界，越陷越深。\n\n有-「與人同者，物必歸焉，故受之以大有。」尋找到志同道合的人，大家齊心協力，就能大有斬獲。\n\n義-「義者，心之制、事之宜也。」義就是人內在的自我規範，顯現於外在就是待人處事合理與適當。\n\n器-「埏埴以為器，當其無，有器之用。」揉和陶土做成器皿，中空，才有器皿的功用。\n\n用最真誠的態度做高品質的精品陶瓷咖啡器皿，串起不同領域的你我，共享生活的美好，就是最有義器的樣子！\n\n",
    "brand.product1.name": "TURBO Coffee Dripper",
    "brand.product1.desc": "利用工業設計的背景，開發保留傳統工藝技術，但不失現代專業咖啡沖煮需求的MIT精品濾杯!\n",
    "brand.product2.name": "甜感渦輪濾杯",
    "brand.product2.desc": "為了咖啡沖煮賽催生的新濾杯!\nTurbo Sweet維持原有特殊斜角設計的堅挺肋骨，\n深度0.5公分加速排氣，流速更順暢 ，\n新設計除了縮小尺寸，不同以往濾杯直通到底的肋骨，\n距離底部3公分處多了1公分長的截斷，\n呈現完美雙渦輪的意象，\n水流抵達截斷高度時，流速減緩，\n使粉水接觸時間增加20%，有利於沖煮時的甜感累積 !",
    "brand.product3.name": "雪楓留香杯",
    "brand.product3.desc": "以往喝咖啡香氣都會隨時間與溫度流失，但留香杯卻顛覆常識「越陳越香」，\n⠀\n極限縮口的設計，不只造型優雅，更能鎖住香氣分子，讓香氣不散、持續聚集，長時間讓香氣在杯內保留迴盪，不論是高溫、中溫或低溫，都極大化的讓咖啡香氣在每一口品嚐中刺激著嗅覺感官，透過外觀、結構還有釉色在視覺、味覺跟觸覺上讓圓潤飽滿的甜感加疊，一直到最後一口，都能滿足我們對手沖精品咖啡的追求！"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "從事工業設計的設計師，因為熱愛手沖咖啡而向台灣烘豆冠軍老師學習了咖啡技術，",
    "brand.summary": "從事工業設計的設計師，因為熱愛手沖咖啡而向台灣烘豆冠軍老師學習了咖啡技術，\n2018年碰上了陶土，就此一頭栽進陶瓷傳統工藝的世界，越陷越深。\n\n有-「與人同者，物必歸焉，故受之以大有。」尋找到志同道合的人，大家齊心協力，就能大有斬獲。\n\n義-「義者，心之制、事之宜也。」義就是人內在的自我規範，顯現於外在就是待人處事合理與適當。\n\n器-「埏埴以為器，當其無，有器之用。」揉和陶土做成器皿，中空，才有器皿的功用。\n\n用最真誠的態度做高品質的精品陶瓷咖啡器皿，串起不同領域的你我，共享生活的美好，就是最有義器的樣子！\n\n",
    "brand.product1.name": "TURBO Coffee Dripper",
    "brand.product1.desc": "利用工業設計的背景，開發保留傳統工藝技術，但不失現代專業咖啡沖煮需求的MIT精品濾杯!\n",
    "brand.product2.name": "TURBO Sweet Coffee Dripper",
    "brand.product2.desc": "為了咖啡沖煮賽催生的新濾杯!\nTurbo Sweet維持原有特殊斜角設計的堅挺肋骨，\n深度0.5公分加速排氣，流速更順暢 ，\n新設計除了縮小尺寸，不同以往濾杯直通到底的肋骨，\n距離底部3公分處多了1公分長的截斷，\n呈現完美雙渦輪的意象，\n水流抵達截斷高度時，流速減緩，\n使粉水接觸時間增加20%，有利於沖煮時的甜感累積 !",
    "brand.product3.name": "Snow Red Aroma Preseving Cup",
    "brand.product3.desc": "以往喝咖啡香氣都會隨時間與溫度流失，但留香杯卻顛覆常識「越陳越香」，\n⠀\n極限縮口的設計，不只造型優雅，更能鎖住香氣分子，讓香氣不散、持續聚集，長時間讓香氣在杯內保留迴盪，不論是高溫、中溫或低溫，都極大化的讓咖啡香氣在每一口品嚐中刺激著嗅覺感官，透過外觀、結構還有釉色在視覺、味覺跟觸覺上讓圓潤飽滿的甜感加疊，一直到最後一口，都能滿足我們對手沖精品咖啡的追求！"
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "從事工業設計的設計師，因為熱愛手沖咖啡而向台灣烘豆冠軍老師學習了咖啡技術，",
    "brand.summary": "從事工業設計的設計師，因為熱愛手沖咖啡而向台灣烘豆冠軍老師學習了咖啡技術，\n2018年碰上了陶土，就此一頭栽進陶瓷傳統工藝的世界，越陷越深。\n\n有-「與人同者，物必歸焉，故受之以大有。」尋找到志同道合的人，大家齊心協力，就能大有斬獲。\n\n義-「義者，心之制、事之宜也。」義就是人內在的自我規範，顯現於外在就是待人處事合理與適當。\n\n器-「埏埴以為器，當其無，有器之用。」揉和陶土做成器皿，中空，才有器皿的功用。\n\n用最真誠的態度做高品質的精品陶瓷咖啡器皿，串起不同領域的你我，共享生活的美好，就是最有義器的樣子！\n\n",
    "brand.product1.name": "TURBO Coffee Dripper",
    "brand.product1.desc": "利用工業設計的背景，開發保留傳統工藝技術，但不失現代專業咖啡沖煮需求的MIT精品濾杯!\n",
    "brand.product2.name": "TURBO Sweet Coffee Dripper",
    "brand.product2.desc": "為了咖啡沖煮賽催生的新濾杯!\nTurbo Sweet維持原有特殊斜角設計的堅挺肋骨，\n深度0.5公分加速排氣，流速更順暢 ，\n新設計除了縮小尺寸，不同以往濾杯直通到底的肋骨，\n距離底部3公分處多了1公分長的截斷，\n呈現完美雙渦輪的意象，\n水流抵達截斷高度時，流速減緩，\n使粉水接觸時間增加20%，有利於沖煮時的甜感累積 !",
    "brand.product3.name": "Snow Red Aroma Preseving Cup",
    "brand.product3.desc": "以往喝咖啡香氣都會隨時間與溫度流失，但留香杯卻顛覆常識「越陳越香」，\n⠀\n極限縮口的設計，不只造型優雅，更能鎖住香氣分子，讓香氣不散、持續聚集，長時間讓香氣在杯內保留迴盪，不論是高溫、中溫或低溫，都極大化的讓咖啡香氣在每一口品嚐中刺激著嗅覺感官，透過外觀、結構還有釉色在視覺、味覺跟觸覺上讓圓潤飽滿的甜感加疊，一直到最後一口，都能滿足我們對手沖精品咖啡的追求！"
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "../../assets/srmark_image/PICABOO_01 - HAO I HSU.jpg" },
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "../../assets/srmark_image/優織隆_鳳梨葉纖維跳色托特包_1- Kelly Tseng.jpg" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "../../assets/srmark_image/ei studio-plant pot-01 - ei studio.png" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "../../assets/srmark_image/DSCF1948 - 元泰工坊.jpg" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "../../assets/srmark_image/賽先生科學工廠-After School - 人體血管分布刺繡套組-01 - Mr. Sci Science Factory.jpg" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "../../assets/srmark_image/P1002357 - Gochi.jpg" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "../../assets/srmark_image/IMG_9086 - 角琉璃.JPG" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "../../assets/srmark_image/20240613 OTOP棒球椅_頁面_1 - liu Alvin (木酢達人 泰逸).jpg" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "../../assets/srmark_image/HEMEL-1 - li Iris.jpg" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w1000" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w1000" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w1000" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+ 優織隆企業股份有限公司", category: "SR MARK Brand", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "SR MARK Brand", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" },
  { name: "Yuantai 元泰竹藝社", category: "SR MARK Brand", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w1000" },
  { name: "Mr.Sci Science Factory 賽先生科學工廠", category: "SR MARK Brand", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
