// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "\"We bring sustainability to sports to infuse into your lifestyle.\"",
    "brand.summary": "\"We bring sustainability to sports to infuse into your lifestyle.\"\n\nDouble Dribble stems from a passion for sports and a commitment to sustainability, transforming basketballs, volleyballs, baseballs, and other retired sports equipment into accessories, lifestyle goods, and handicraft.\n\nThrough design, upcycling, and creativity, we provide a brand new sports waste upcycling system that allows sport related goods at the end of their life cycle to check back in the game.",
    "brand.product1.name": "Carry: Upcycled Basketball Phone Pouch",
    "brand.product1.desc": "Carry: Upcycled Basketball Phone Pouch is crafted using traditional leather techniques using upcycled basketball materials. More than 90% of the pouch is made from upcycled materials, with the main structure formed from a basketball’s inner rubber bladder and an outer layer that highlights each piece’s distinctive colorway. Each piece of basketball material carries its own journey. From textures, symbols, marks, scratches, and colors, every visible detail tells the story of an athlete and their memories, a connection made possible through sustainability.",
    "brand.product2.name": "Overtime (OT): Upcycled Card Holder and DIY Kit",
    "brand.product2.desc": "Overtime (OT) is a customizable card holder designed to reflect your sport of choice. Made with more than 90% upcycled ball materials, OT can be crafted from recycled sports balls such as basketballs, volleyballs, and footballs. The DIY kit offers a hands-on upcycling experience, letting you choose your preferred ball material and create your own card holder using leathercraft techniques like sewing, hole punching, and basic assembly. Make your own upcycled card holder and join the sports sustainability cycle.",
    "brand.product3.name": "Upcycled Gametime Accessories",
    "brand.product3.desc": "These accessories are an intuitive way to tackle sports waste. They are made from upcycled materials, including basketballs, volleyballs, footballs, baseballs, tennis balls, pickleballs, and more, collected from schools and businesses across Taiwan. The collection includes trophies, medallions, and themed gifts for media, players, and fans. Upcycling preserves the original texture, and the pieces can be customized through collaborations, allowing event logos or names to be featured on the upcycled goods. Sports is more than just a game, and sustainability is more than just a concept. Let us enhance the experience together for a better future."
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "「將永續帶給運動，讓運動成為生活。」",
    "brand.summary": "「將永續帶給運動，讓運動成為生活。」\n\n二次運球源自對運動的熱愛與永續的承諾，使用台灣校園和運動產業丟棄的籃球、排球、棒球、足球、網球...等體育耗材，打造為服飾配件、生活用品與手作媒材，透過設計、回收與再製，體現一個全新的球類回收機制，讓生命終結的球類重新上場。",
    "brand.product1.name": "Carry 升級回收籃球手機袋",
    "brand.product1.desc": "Carry手機袋是一個結合傳統皮革工藝和運動永續媒材的作品，90%以上使用回收籃球皮料製成，拆解籃球內膽作為主體結構，外層球皮裁版密縫為袋體外觀特徵，回收籃球皮料有著各種顏色、紋理、圖騰和運動過程的使用痕跡，每一件Carry手機袋都是獨一無二的，傳遞著運動員的故事、記憶與永續價值。",
    "brand.product2.name": "升級回收OT球類識別證套與材料包系列",
    "brand.product2.desc": "OT球類識別證套是一個具備運動永續概念與手作體驗的作品，90%以上使用升級回收的運動廢棄物製作而成，如籃球、排球、足球… 。除了可直接使用的成品外，也同步推出識別證套體驗課程與手作材料包，邀請大家挑選喜歡的球料，透過運動媒材的裁切、手縫、五金組裝等技法，創作專屬的升級回收識別證套，親身體驗永續工藝的樂趣。",
    "brand.product3.name": "升級回收運動周邊系列",
    "brand.product3.desc": "這是一個讓運動產業的耗材重新回到運動市場的循環商品系列，使用台灣校園與運動產業產出的體育廢棄物：籃球、排球、棒球、網球、足球、匹克球... ，製作成各種運動賽事周邊商品，如獎盃、獎牌、媒體和球迷禮品，保留運動媒材原始的樣貌並透過與運動IP的合作，讓生命終結的球類重新上場。運動不只是比賽，永續不只是口號，一起為未來做出改變吧！"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "\"We bring sustainability to sports to infuse into your lifestyle.\"",
    "brand.summary": "\"We bring sustainability to sports to infuse into your lifestyle.\"\n\nDouble Dribble stems from a passion for sports and a commitment to sustainability, transforming basketballs, volleyballs, baseballs, and other retired sports equipment into accessories, lifestyle goods, and handicraft.\n\nThrough design, upcycling, and creativity, we provide a brand new sports waste upcycling system that allows sport related goods at the end of their life cycle to check back in the game.",
    "brand.product1.name": "Carry: Upcycled Basketball Phone Pouch",
    "brand.product1.desc": "Carry: Upcycled Basketball Phone Pouch is crafted using traditional leather techniques using upcycled basketball materials. More than 90% of the pouch is made from upcycled materials, with the main structure formed from a basketball’s inner rubber bladder and an outer layer that highlights each piece’s distinctive colorway. Each piece of basketball material carries its own journey. From textures, symbols, marks, scratches, and colors, every visible detail tells the story of an athlete and their memories, a connection made possible through sustainability.",
    "brand.product2.name": "Overtime (OT): Upcycled Card Holder and DIY Kit",
    "brand.product2.desc": "Overtime (OT) is a customizable card holder designed to reflect your sport of choice. Made with more than 90% upcycled ball materials, OT can be crafted from recycled sports balls such as basketballs, volleyballs, and footballs. The DIY kit offers a hands-on upcycling experience, letting you choose your preferred ball material and create your own card holder using leathercraft techniques like sewing, hole punching, and basic assembly. Make your own upcycled card holder and join the sports sustainability cycle.",
    "brand.product3.name": "Upcycled Gametime Accessories",
    "brand.product3.desc": "These accessories are an intuitive way to tackle sports waste. They are made from upcycled materials, including basketballs, volleyballs, footballs, baseballs, tennis balls, pickleballs, and more, collected from schools and businesses across Taiwan. The collection includes trophies, medallions, and themed gifts for media, players, and fans. Upcycling preserves the original texture, and the pieces can be customized through collaborations, allowing event logos or names to be featured on the upcycled goods. Sports is more than just a game, and sustainability is more than just a concept. Let us enhance the experience together for a better future."
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "\"We bring sustainability to sports to infuse into your lifestyle.\"",
    "brand.summary": "\"We bring sustainability to sports to infuse into your lifestyle.\"\n\nDouble Dribble stems from a passion for sports and a commitment to sustainability, transforming basketballs, volleyballs, baseballs, and other retired sports equipment into accessories, lifestyle goods, and handicraft.\n\nThrough design, upcycling, and creativity, we provide a brand new sports waste upcycling system that allows sport related goods at the end of their life cycle to check back in the game.",
    "brand.product1.name": "Carry: Upcycled Basketball Phone Pouch",
    "brand.product1.desc": "Carry: Upcycled Basketball Phone Pouch is crafted using traditional leather techniques using upcycled basketball materials. More than 90% of the pouch is made from upcycled materials, with the main structure formed from a basketball’s inner rubber bladder and an outer layer that highlights each piece’s distinctive colorway. Each piece of basketball material carries its own journey. From textures, symbols, marks, scratches, and colors, every visible detail tells the story of an athlete and their memories, a connection made possible through sustainability.",
    "brand.product2.name": "Overtime (OT): Upcycled Card Holder and DIY Kit",
    "brand.product2.desc": "Overtime (OT) is a customizable card holder designed to reflect your sport of choice. Made with more than 90% upcycled ball materials, OT can be crafted from recycled sports balls such as basketballs, volleyballs, and footballs. The DIY kit offers a hands-on upcycling experience, letting you choose your preferred ball material and create your own card holder using leathercraft techniques like sewing, hole punching, and basic assembly. Make your own upcycled card holder and join the sports sustainability cycle.",
    "brand.product3.name": "Upcycled Gametime Accessories",
    "brand.product3.desc": "These accessories are an intuitive way to tackle sports waste. They are made from upcycled materials, including basketballs, volleyballs, footballs, baseballs, tennis balls, pickleballs, and more, collected from schools and businesses across Taiwan. The collection includes trophies, medallions, and themed gifts for media, players, and fans. Upcycling preserves the original texture, and the pieces can be customized through collaborations, allowing event logos or names to be featured on the upcycled goods. Sports is more than just a game, and sustainability is more than just a concept. Let us enhance the experience together for a better future."
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "../../assets/srmark_image/PICABOO_01 - HAO I HSU.jpg" },
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "../../assets/srmark_image/優織隆_鳳梨葉纖維跳色托特包_1- Kelly Tseng.jpg" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "../../assets/srmark_image/ei studio-plant pot-01 - ei studio.png" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "../../assets/srmark_image/DSCF1948 - 元泰工坊.jpg" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "../../assets/srmark_image/賽先生科學工廠-After School - 人體血管分布刺繡套組-01 - Mr. Sci Science Factory.jpg" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "../../assets/srmark_image/有義器_渦輪濾杯_1 - Rhea Chou.jpg" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "../../assets/srmark_image/P1002357 - Gochi.jpg" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "../../assets/srmark_image/IMG_9086 - 角琉璃.JPG" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "../../assets/srmark_image/20240613 OTOP棒球椅_頁面_1 - liu Alvin (木酢達人 泰逸).jpg" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "../../assets/srmark_image/HEMEL-1 - li Iris.jpg" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w400" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w400" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w400" },
  { name: "EVOPURE+ 優織隆企業股份有限公司", category: "SR MARK Brand", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w400" },
  { name: "ei studio", category: "SR MARK Brand", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w400" },
  { name: "Yuantai 元泰竹藝社", category: "SR MARK Brand", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w400" },
  { name: "Mr.Sci Science Factory 賽先生科學工廠", category: "SR MARK Brand", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w400" },
  { name: "GUTS STUDIO 有義器", category: "SR MARK Brand", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w400" },
  { name: "ECOJOY", category: "SR MARK Brand", folder: "7-ECOJOY", image: "https://drive.google.com/thumbnail?id=1fu8za9qt7vSoVVp2eGyy3X6SGssJdNyW&sz=w400" },
  { name: "JIAO 角琉璃", category: "SR MARK Brand", folder: "8-JIAO", image: "https://drive.google.com/thumbnail?id=1JSh9469-8TcrtswUQCt8lOnkcEpgiyrR&sz=w400" },
  { name: "REWOOD Forest Cycle REWOOD森林循環", category: "SR MARK Brand", folder: "9-REWOOD", image: "https://drive.google.com/thumbnail?id=1lNf4a32YEWEf-X1HMMoUDBU06w1yr4pR&sz=w400" },
  { name: "HongJi Box Art Co., Ltd 宏吉盒藝有限公司", category: "SR MARK Brand", folder: "10-HONGJI", image: "https://drive.google.com/thumbnail?id=1J9nMzczqJ0qBV6YhNthCuxbEyN66pmPF&sz=w400" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
