// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Hongji has specialized in gift box packaging for 48 years. ",
    "brand.summary": "Hongji has specialized in gift box packaging for 48 years. \nOur founding principle is \"Your one and only\" and we have earned widespread acclaim for our diverse box designs and high quality. \nIn 2018, we established the \"HongJi Box Art\" brand.\nHong Ji Box Art - Package design with a thoughtful touch.\nWe believe that a perfect package doesn’t mean Over-designing.\nTaking every clients brand DNA and their product feature to consideration.\nAnd combine traditional box design structure with modern graphic design.\nWe strive to deliver a tailor-made package for each product with a taste of its own.",
    "brand.product1.name": "HEMEL Tea Drink Gift Box",
    "brand.product1.desc": "HEMEL, pioneering an imaginative tea-drinking experience. The ingredients are exclusively sourced from renowned tea gardens, featuring unique and exceptionally rare tea leaves. These precious leaves are handcrafted and blended to release their beautifully clear and distinct aroma.\nAt HEMEL, we possess a profound appreciation for the profound influence packaging exerts upon the environment. Therefore, we actively strive to enhance the sustainability of our packaging and minimize the burden on the environment. We maximize the use of recyclable paper and paper made from recycled materials, avoiding extravagant printing and decorative processes. From the manufacturing stage, we aim to reduce ink usage and limit printing and processing to the necessary minimum. Furthermore, to ensure maximum recycling, we make efforts to avoid coating the surface of the paper."
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "宏吉專營包裝禮盒48年，「不做第一，只作唯一」是我們創業初衷，以多樣性盒型與高品質深獲好評。於2018年成立「HongJi Box Art 宏吉盒藝」品牌，想做的不單是禮盒包裝而是帶有品牌靈魂的藝術品，除了持續將客戶品牌DNA及產品特色融入包裝其中，更為每個成品量身訂作符合品味的包裝盒。透過手工打造獨一無二的盒藝，展露客戶獨特的品味。",
    "brand.summary": "宏吉專營包裝禮盒48年，「不做第一，只作唯一」是我們創業初衷，以多樣性盒型與高品質深獲好評。於2018年成立「HongJi Box Art 宏吉盒藝」品牌，想做的不單是禮盒包裝而是帶有品牌靈魂的藝術品，除了持續將客戶品牌DNA及產品特色融入包裝其中，更為每個成品量身訂作符合品味的包裝盒。透過手工打造獨一無二的盒藝，展露客戶獨特的品味。",
    "brand.product1.name": "HEMEL 茶飲禮盒",
    "brand.product1.desc": "HEMEL，開創想像的茶飲體驗. 原料僅有來自名門茶園中蘊含個性、頂級珍稀的茶葉。珍貴的茶葉透過手工調製揉和，散發出茶香優美清晰的輪廓。在HEMEL，我們也深知包裝對環境的深遠影響。因此，我們積極致力於提升包裝的可持續性，並盡可能減少對環境的負擔。我們最大限度地使用可回收紙和再生紙，避免過度印刷和裝飾。從生產階段開始，我們就力求減少油墨用量，並將印刷和加工工序精簡到必要的最低限度。此外，為了確保最大程度的回收利用，我們努力避免對紙張表面進行塗層處理。"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Hongji has specialized in gift box packaging for 48 years. ",
    "brand.summary": "Hongji has specialized in gift box packaging for 48 years. \nOur founding principle is \"Your one and only\" and we have earned widespread acclaim for our diverse box designs and high quality. \nIn 2018, we established the \"HongJi Box Art\" brand.\nHong Ji Box Art - Package design with a thoughtful touch.\nWe believe that a perfect package doesn’t mean Over-designing.\nTaking every clients brand DNA and their product feature to consideration.\nAnd combine traditional box design structure with modern graphic design.\nWe strive to deliver a tailor-made package for each product with a taste of its own.",
    "brand.product1.name": "HEMEL Tea Drink Gift Box",
    "brand.product1.desc": "HEMEL, pioneering an imaginative tea-drinking experience. The ingredients are exclusively sourced from renowned tea gardens, featuring unique and exceptionally rare tea leaves. These precious leaves are handcrafted and blended to release their beautifully clear and distinct aroma.\nAt HEMEL, we possess a profound appreciation for the profound influence packaging exerts upon the environment. Therefore, we actively strive to enhance the sustainability of our packaging and minimize the burden on the environment. We maximize the use of recyclable paper and paper made from recycled materials, avoiding extravagant printing and decorative processes. From the manufacturing stage, we aim to reduce ink usage and limit printing and processing to the necessary minimum. Furthermore, to ensure maximum recycling, we make efforts to avoid coating the surface of the paper."
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "Hongji has specialized in gift box packaging for 48 years. ",
    "brand.summary": "Hongji has specialized in gift box packaging for 48 years. \nOur founding principle is \"Your one and only\" and we have earned widespread acclaim for our diverse box designs and high quality. \nIn 2018, we established the \"HongJi Box Art\" brand.\nHong Ji Box Art - Package design with a thoughtful touch.\nWe believe that a perfect package doesn’t mean Over-designing.\nTaking every clients brand DNA and their product feature to consideration.\nAnd combine traditional box design structure with modern graphic design.\nWe strive to deliver a tailor-made package for each product with a taste of its own.",
    "brand.product1.name": "HEMEL Tea Drink Gift Box",
    "brand.product1.desc": "HEMEL, pioneering an imaginative tea-drinking experience. The ingredients are exclusively sourced from renowned tea gardens, featuring unique and exceptionally rare tea leaves. These precious leaves are handcrafted and blended to release their beautifully clear and distinct aroma.\nAt HEMEL, we possess a profound appreciation for the profound influence packaging exerts upon the environment. Therefore, we actively strive to enhance the sustainability of our packaging and minimize the burden on the environment. We maximize the use of recyclable paper and paper made from recycled materials, avoiding extravagant printing and decorative processes. From the manufacturing stage, we aim to reduce ink usage and limit printing and processing to the necessary minimum. Furthermore, to ensure maximum recycling, we make efforts to avoid coating the surface of the paper."
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "../../assets/srmark_image/PICABOO_01 - HAO I HSU.jpg" },
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "../../assets/srmark_image/優織隆_鳳梨葉纖維跳色托特包_1- Kelly Tseng.jpg" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "../../assets/srmark_image/ei studio-plant pot-01 - ei studio.png" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "../../assets/srmark_image/DSCF1948 - 元泰工坊.jpg" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "../../assets/srmark_image/賽先生科學工廠-After School - 人體血管分布刺繡套組-01 - Mr. Sci Science Factory.jpg" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "../../assets/srmark_image/有義器_渦輪濾杯_1 - Rhea Chou.jpg" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "../../assets/srmark_image/P1002357 - Gochi.jpg" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "../../assets/srmark_image/IMG_9086 - 角琉璃.JPG" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "../../assets/srmark_image/20240613 OTOP棒球椅_頁面_1 - liu Alvin (木酢達人 泰逸).jpg" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "../../assets/srmark_image/HEMEL-1 - li Iris.jpg" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w1000" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w1000" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w1000" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+ 優織隆企業股份有限公司", category: "SR MARK Brand", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "SR MARK Brand", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" },
  { name: "Yuantai 元泰竹藝社", category: "SR MARK Brand", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w1000" },
  { name: "Mr.Sci Science Factory 賽先生科學工廠", category: "SR MARK Brand", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" },
  { name: "GUTS STUDIO 有義器", category: "SR MARK Brand", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w1000" },
  { name: "ECOJOY", category: "SR MARK Brand", folder: "7-ECOJOY", image: "https://drive.google.com/thumbnail?id=1fu8za9qt7vSoVVp2eGyy3X6SGssJdNyW&sz=w1000" },
  { name: "JIAO 角琉璃", category: "SR MARK Brand", folder: "8-JIAO", image: "https://drive.google.com/thumbnail?id=1JSh9469-8TcrtswUQCt8lOnkcEpgiyrR&sz=w1000" },
  { name: "REWOOD Forest Cycle REWOOD森林循環", category: "SR MARK Brand", folder: "9-REWOOD", image: "https://drive.google.com/thumbnail?id=1lNf4a32YEWEf-X1HMMoUDBU06w1yr4pR&sz=w1000" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
