// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Founded in 2021, Jiao  is a contemporary craft brand based on Taiwan’s eastern coast. Centered around glass craftsmanship, the brand combines Paiwan bead culture, Austronesian aesthetics, and contempo",
    "brand.summary": "Founded in 2021, Jiao  is a contemporary craft brand based on Taiwan’s eastern coast. Centered around glass craftsmanship, the brand combines Paiwan bead culture, Austronesian aesthetics, and contemporary design language to create works that balance craftsmanship with everyday wearability.\nJiao explores the relationship between material, color, and cultural memory through handmade glass works. Inspired by island life, oceanic atmosphere, and cultural patterns, the brand transforms these elements into contemporary craft objects that can be worn, carried, and experienced in daily life. Each piece preserves the traces of handcraft and the warmth of its material, while continuing to seek new expressions between traditional craft and contemporary living.\nIn recent years, Jiao has participated in exhibitions, markets, and international cultural exchanges across Taiwan and abroad, including Japan, Chiang Mai, and Singapore, gradually shaping its own craft aesthetic and distinctive brand identity.",
    "brand.product1.name": "sunrise",
    "brand.product1.desc": "Inspired by traditional Paiwan patterns and the landscape of Taimali on Taiwan’s eastern coast, Sunrise reflects the colors, light, and atmosphere of island life through handmade glass beads. Flowing lines and layered colors echo the movement of sunrise across the ocean and mountains, while carrying cultural motifs connected to nature, protection, and continuity.\nEach bead is individually handmade in flame, preserving the organic traces, depth, and warmth of glass as a living material. Through shifting color and pattern, the work captures changing landscapes and moments of light found along the coast.\nMore than jewelry, Sunrise is a contemporary craft piece shaped by cultural memory, everyday wear, and the rhythm of island life."
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "角琉璃成立於2021年，為來自台灣東海岸的當代文化工藝品牌。品牌以玻璃工藝為核心，結合排灣族琉璃珠文化、南島美學與當代設計語彙，創作兼具工藝性與日常佩戴感的作品。",
    "brand.summary": "角琉璃成立於2021年，為來自台灣東海岸的當代文化工藝品牌。品牌以玻璃工藝為核心，結合排灣族琉璃珠文化、南島美學與當代設計語彙，創作兼具工藝性與日常佩戴感的作品。\n角琉璃長期關注材料、色彩與文化記憶之間的關係，透過玻璃與手工製作，將島嶼生活、海洋氣息與文化紋飾轉譯為可被感受與攜帶的當代工藝語言。作品保留手工痕跡與材料溫度，也持續在傳統工藝與當代生活之間尋找新的表達方式。\n近年持續參與台灣各地展售、市集與跨國文化交流，並曾於日本、清邁與新加坡等地進行展售與合作，逐步建立屬於角琉璃的工藝美學與品牌風格。",
    "brand.product1.name": "《日昇》以排灣族傳統紋飾為靈感，結合太麻里海岸的光線、山海景色與土地記憶進行創作。作品中的色彩與紋路，回應著日出時海面與山脈交會的流動感，也延續排灣族琉璃珠中對自然、守護與生命循環的文化意象。 每一顆珠子皆以手工製作完成，保留玻璃在火焰中流動的痕跡與溫度。不同色彩之間的排列，如同土地上的風景與時間的變化，在配戴與觀看之間持續產生新的感受。 《日昇》不只是飾品，也是一件來自島嶼生活與文化記憶的當代工藝作品。透過玻璃與色彩，將太麻里的海洋、陽光與文化紋飾轉譯為能被攜帶與感受的日常物件。",
    "brand.product1.desc": "《日昇》以排灣族傳統紋飾為靈感，結合太麻里海岸的光線、山海景色與土地記憶進行創作。作品中的色彩與紋路，回應著日出時海面與山脈交會的流動感，也延續排灣族琉璃珠中對自然、守護與生命循環的文化意象。\n每一顆珠子皆以手工製作完成，保留玻璃在火焰中流動的痕跡與溫度。不同色彩之間的排列，如同土地上的風景與時間的變化，在配戴與觀看之間持續產生新的感受。\n《日昇》不只是飾品，也是一件來自島嶼生活與文化記憶的當代工藝作品。透過玻璃與色彩，將太麻里的海洋、陽光與文化紋飾轉譯為能被攜帶與感受的日常物件。"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Jiao, opgericht in 2021, is een eigentijds ambachtsmerk van de oostkust van Taiwan, dat glaskunst combineert met Paiwan-kraalcultuur en Austronesische esthetiek.",
    "brand.summary": "Jiao, opgericht in 2021, is een eigentijds ambachtsmerk van de oostkust van Taiwan. Met glaskunst als kern combineert het merk Paiwan-kraalcultuur, Austronesische esthetiek en hedendaagse designtaal om werken te creeren die ambachtselijkheid en dagelijkse draagbaarheid combineren.\nJiao verkent de relatie tussen materiaal, kleur en cultureel geheugen via handgemaakte glaswerken. Geïnspireerd door eilandleven, oceaansfeer en culturele patronen transformeert het merk deze elementen in hedendaagse ambachtsobjecten die gedragen en beleefd kunnen worden. Elk stuk bewaart de sporen van handwerk en de warmte van het materiaal.\nDe afgelopen jaren heeft Jiao deelgenomen aan tentoonstellingen en internationale culturele uitwisselingen in Taiwan en daarbuiten, waaronder Japan, Chiang Mai en Singapore.",
    "brand.product1.name": "sunrise",
    "brand.product1.desc": "Inspired by traditional Paiwan patterns and the landscape of Taimali on Taiwan’s eastern coast, Sunrise reflects the colors, light, and atmosphere of island life through handmade glass beads. Flowing lines and layered colors echo the movement of sunrise across the ocean and mountains, while carrying cultural motifs connected to nature, protection, and continuity.\nEach bead is individually handmade in flame, preserving the organic traces, depth, and warmth of glass as a living material. Through shifting color and pattern, the work captures changing landscapes and moments of light found along the coast.\nMore than jewelry, Sunrise is a contemporary craft piece shaped by cultural memory, everyday wear, and the rhythm of island life."
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "2021\u5e74\u8a2d\u7acbのJiao\uff08\u89d2\u7409\u74a8\uff09\u306f\u3001\u53f0\u6e7e\u6771\u6d77\u5cb8\u3092\u62e0\u70b9\u3068\u3059\u308b\u73fe\u4ee3\u5de5\u82b8\u30d6\u30e9\u30f3\u30c9\u3067\u3001\u30ac\u30e9\u30b9\u5de5\u82b8\u3092\u30d1\u30a4\u30ef\u30f3\u65cf\u306e\u7409\u74a8\u73e0\u6587\u5316\u3084\u30aa\u30fc\u30b9\u30c8\u30ed\u30cd\u30b7\u30a2\u7f8e\u5b66\u3068\u878d\u5408\u3055\u305b\u3066\u3044\u307e\u3059\u3002",
    "brand.summary": "2021\u5e74\u8a2d\u7acbのJiao\uff08\u89d2\u7409\u74a8\uff09\u306f\u3001\u53f0\u6e7e\u6771\u6d77\u5cb8\u3092\u62e0\u70b9\u3068\u3059\u308b\u73fe\u4ee3\u5de5\u82b8\u30d6\u30e9\u30f3\u30c9\u3067\u3059\u3002\u30ac\u30e9\u30b9\u5de5\u82b8\u3092\u6838\u5fc3\u3068\u3057\u3001\u30d1\u30a4\u30ef\u30f3\u65cf\u306e\u7409\u74a8\u73e0\u6587\u5316\u3001\u30aa\u30fc\u30b9\u30c8\u30ed\u30cd\u30b7\u30a2\u7f8e\u5b66\u3001\u73fe\u4ee3\u30c7\u30b6\u30a4\u30f3\u306e\u8a9e\u5f59\u3092\u7d44\u307f\u5408\u308f\u305b\u3001\u5de5\u82b8\u6027\u3068\u65e5\u5e38\u7684\u306a\u88c5\u98fe\u611f\u3092\u517c\u306d\u5099\u3048\u305f\u4f5c\u54c1\u3092\u751f\u307f\u51fa\u3057\u3066\u3044\u307e\u3059\u3002\nJiao\u306f\u624b\u4f5c\u308a\u306e\u30ac\u30e9\u30b9\u4f5c\u54c1\u3092\u901a\u3057\u3066\u7d20\u6750\u30fb\u8272\u30fb\u6587\u5316\u7684\u8a18\u61b6\u306e\u95a2\u4fc2\u3092\u63a2\u6c42\u3057\u3066\u3044\u307e\u3059\u3002\u5cf6\u306e\u66ae\u3089\u3057\u3001\u6d77\u306e\u96f0\u56f2\u6c17\u3001\u6587\u5316\u7684\u30d1\u30bf\u30fc\u30f3\u306b\u30a4\u30f3\u30b9\u30d1\u30a4\u30a2\u3055\u308c\u3001\u3053\u308c\u3089\u3092\u65e5\u5e38\u7684\u306b\u8eab\u306b\u7740\u3051\u308b\u73fe\u4ee3\u7684\u306a\u5de5\u82b8\u54c1\u3078\u3068\u5909\u63db\u3057\u3066\u3044\u307e\u3059\u3002\n\u8fd1\u5e74\u3001Jiao\u306f\u65e5\u672c\u30fb\u30c1\u30a7\u30f3\u30de\u30a4\u30fb\u30b7\u30f3\u30ac\u30dd\u30fc\u30eb\u306a\u3069\u56fd\u5185\u5916\u306e\u5c55\u793a\u4f1a\u30fb\u30de\u30fc\u30b1\u30c3\u30c8\u30fb\u56fd\u969b\u6587\u5316\u4ea4\u6d41\u306b\u53c2\u52a0\u3057\u3001\u72ec\u81ea\u306e\u5de5\u82b8\u7f8e\u5b66\u3068\u30d6\u30e9\u30f3\u30c9\u30a2\u30a4\u30c7\u30f3\u30c6\u30a3\u30c6\u30a3\u3092\u5f62\u6210\u3057\u3066\u304d\u307e\u3057\u305f\u3002",
    "brand.product1.name": "sunrise",
    "brand.product1.desc": "Inspired by traditional Paiwan patterns and the landscape of Taimali on Taiwan’s eastern coast, Sunrise reflects the colors, light, and atmosphere of island life through handmade glass beads. Flowing lines and layered colors echo the movement of sunrise across the ocean and mountains, while carrying cultural motifs connected to nature, protection, and continuity.\nEach bead is individually handmade in flame, preserving the organic traces, depth, and warmth of glass as a living material. Through shifting color and pattern, the work captures changing landscapes and moments of light found along the coast.\nMore than jewelry, Sunrise is a contemporary craft piece shaped by cultural memory, everyday wear, and the rhythm of island life."
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w1000" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w1000" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "https://drive.google.com/thumbnail?id=1fu8za9qt7vSoVVp2eGyy3X6SGssJdNyW&sz=w1000" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "https://drive.google.com/thumbnail?id=1lNf4a32YEWEf-X1HMMoUDBU06w1yr4pR&sz=w1000" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "https://drive.google.com/thumbnail?id=1J9nMzczqJ0qBV6YhNthCuxbEyN66pmPF&sz=w1000" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w1000" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w1000" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w1000" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+ 優織隆企業股份有限公司", category: "SR MARK Brand", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "SR MARK Brand", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" },
  { name: "Yuantai 元泰竹藝社", category: "SR MARK Brand", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w1000" },
  { name: "Mr.Sci Science Factory 賽先生科學工廠", category: "SR MARK Brand", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" },
  { name: "GUTS STUDIO 有義器", category: "SR MARK Brand", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w1000" },
  { name: "ECOJOY", category: "SR MARK Brand", folder: "7-ECOJOY", image: "https://drive.google.com/thumbnail?id=1fu8za9qt7vSoVVp2eGyy3X6SGssJdNyW&sz=w1000" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
