// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Founded in 2023, ECOJOY is dedicated to transforming 100% post-industrial recycled plastic into a wide range of innovative products. More than just a slogan or an environmental action, ECOJOY brings s",
    "brand.summary": "Founded in 2023, ECOJOY is dedicated to transforming 100% post-industrial recycled plastic into a wide range of innovative products. More than just a slogan or an environmental action, ECOJOY brings sustainability into everyday life through creative design and practical applications, adding joy and fun to daily living.",
    "brand.product1.name": "Circular Coaster",
    "brand.product1.desc": "ECOJOY秉持著對循環及新創產業的熱忱，奔走各方連結各類產業，著手將地球垃圾變成無限可能。ECOJOY從台灣小島出發，腳踏這片土地推及世界各地，創造與環境永續共存的綠生活，讓物件價值延續到生活儀式中。\n",
    "brand.product2.name": "ECO CHAIR",
    "brand.product2.desc": "Eco-chair 是由一片椅板和兩片椅腳組合而成，透過對位切割及卡榫組裝，無使用任何螺絲或五金件加工。一方面落實環保義務，讓曾經的廢棄成為生活日常；另一方面透過巧妙的設計，讓使用者能自由組裝出多種獨特的樣式，並具備易拆解與收納之特性，既實用又具美感。"
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "ECOJOY 創立於 2023 年，致力於將 100% 產業回收塑膠，做成各類新型態產品為核心，讓環保不僅是口號和行動，更從創新設計切入結合日常應用，替生活帶來快樂及趣味。",
    "brand.summary": "ECOJOY 創立於 2023 年，致力於將 100% 產業回收塑膠，做成各類新型態產品為核心，讓環保不僅是口號和行動，更從創新設計切入結合日常應用，替生活帶來快樂及趣味。",
    "brand.product1.name": "循環杯墊",
    "brand.product1.desc": "ECOJOY秉持著對循環及新創產業的熱忱，奔走各方連結各類產業，著手將地球垃圾變成無限可能。ECOJOY從台灣小島出發，腳踏這片土地推及世界各地，創造與環境永續共存的綠生活，讓物件價值延續到生活儀式中。\n",
    "brand.product2.name": "斑斕彩凳",
    "brand.product2.desc": "Eco-chair 是由一片椅板和兩片椅腳組合而成，透過對位切割及卡榫組裝，無使用任何螺絲或五金件加工。一方面落實環保義務，讓曾經的廢棄成為生活日常；另一方面透過巧妙的設計，讓使用者能自由組裝出多種獨特的樣式，並具備易拆解與收納之特性，既實用又具美感。"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "ECOJOY, opgericht in 2023, is toegewijd aan het omzetten van 100% post-industrieel gerecycled plastic in een breed scala aan innovatieve producten.",
    "brand.summary": "ECOJOY, opgericht in 2023, is toegewijd aan het omzetten van 100% post-industrieel gerecycled plastic in een breed scala aan innovatieve producten. Meer dan alleen een slogan of een milieuactie, brengt ECOJOY duurzaamheid in het dagelijks leven via creatief ontwerp en praktische toepassingen, en voegt vreugde en plezier toe aan het dagelijks leven.",
    "brand.product1.name": "Circular Coaster",
    "brand.product1.desc": "ECOJOY秉持著對循環及新創產業的熱忱，奔走各方連結各類產業，著手將地球垃圾變成無限可能。ECOJOY從台灣小島出發，腳踏這片土地推及世界各地，創造與環境永續共存的綠生活，讓物件價值延續到生活儀式中。\n",
    "brand.product2.name": "ECO CHAIR",
    "brand.product2.desc": "Eco-chair 是由一片椅板和兩片椅腳組合而成，透過對位切割及卡榫組裝，無使用任何螺絲或五金件加工。一方面落實環保義務，讓曾經的廢棄成為生活日常；另一方面透過巧妙的設計，讓使用者能自由組裝出多種獨特的樣式，並具備易拆解與收納之特性，既實用又具美感。"
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "2023\u5e74\u8a2d\u7acbのECOJOY\u306f\u3001100%\u7523\u696d\u56de\u53ce\u30d7\u30e9\u30b9\u30c1\u30c3\u30af\u3092\u3055\u307e\u3056\u307e\u306a\u9769\u65b0\u7684\u306a\u88fd\u54c1\u3078\u3068\u5909\u63db\u3059\u308b\u3053\u3068\u306b\u53d6\u308a\u7d44\u3093\u3067\u3044\u307e\u3059\u3002",
    "brand.summary": "2023\u5e74\u8a2d\u7acbのECOJOY\u306f\u3001100%\u7523\u696d\u56de\u53ce\u30d7\u30e9\u30b9\u30c1\u30c3\u30af\u3092\u3055\u307e\u3056\u307e\u306a\u9769\u65b0\u7684\u306a\u88fd\u54c1\u3078\u3068\u5909\u63db\u3059\u308b\u3053\u3068\u3092\u4f7f\u547d\u3068\u3057\u3066\u3044\u307e\u3059\u3002\u74b0\u5883\u3078\u306e\u53d6\u308a\u7d44\u307f\u306f\u30b9\u30ed\u30fc\u30ac\u30f3\u3084\u884c\u52d5\u306b\u7559\u307e\u3089\u305a\u3001\u30af\u30ea\u30a8\u30a4\u30c6\u30a3\u30d6\u306a\u30c7\u30b6\u30a4\u30f3\u3068\u5b9f\u7528\u7684\u306a\u5fdc\u7528\u3092\u901a\u3058\u3066\u30b5\u30b9\u30c6\u30ca\u30d3\u30ea\u30c6\u30a3\u3092\u65e5\u5e38\u751f\u6d3b\u306b\u53d6\u308a\u8fbc\u307f\u3001\u6bce\u65e5\u306b\u55dc\u3073\u3068\u697d\u3057\u3055\u3092\u52a0\u3048\u3066\u3044\u307e\u3059\u3002",
    "brand.product1.name": "Circular Coaster",
    "brand.product1.desc": "ECOJOY秉持著對循環及新創產業的熱忱，奔走各方連結各類產業，著手將地球垃圾變成無限可能。ECOJOY從台灣小島出發，腳踏這片土地推及世界各地，創造與環境永續共存的綠生活，讓物件價值延續到生活儀式中。\n",
    "brand.product2.name": "ECO CHAIR",
    "brand.product2.desc": "Eco-chair 是由一片椅板和兩片椅腳組合而成，透過對位切割及卡榫組裝，無使用任何螺絲或五金件加工。一方面落實環保義務，讓曾經的廢棄成為生活日常；另一方面透過巧妙的設計，讓使用者能自由組裝出多種獨特的樣式，並具備易拆解與收納之特性，既實用又具美感。"
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w1000" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w1000" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "https://drive.google.com/thumbnail?id=1JSh9469-8TcrtswUQCt8lOnkcEpgiyrR&sz=w1000" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "https://drive.google.com/thumbnail?id=1lNf4a32YEWEf-X1HMMoUDBU06w1yr4pR&sz=w1000" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "https://drive.google.com/thumbnail?id=1J9nMzczqJ0qBV6YhNthCuxbEyN66pmPF&sz=w1000" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w1000" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w1000" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w1000" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+ 優織隆企業股份有限公司", category: "SR MARK Brand", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "SR MARK Brand", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" },
  { name: "Yuantai 元泰竹藝社", category: "SR MARK Brand", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w1000" },
  { name: "Mr.Sci Science Factory 賽先生科學工廠", category: "SR MARK Brand", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" },
  { name: "GUTS STUDIO 有義器", category: "SR MARK Brand", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w1000" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
