// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "The moment a child first grips a spoon on their own — around age one — something important is already happening. The small muscles in their hand are beginning years of quiet, daily practice. Long befo",
    "brand.summary": "The moment a child first grips a spoon on their own — around age one — something important is already happening. The small muscles in their hand are beginning years of quiet, daily practice. Long before they ever pick up a pencil, the table is where fine motor development begins.\n\nWe built CYD TERRA around that moment.\nEvery piece in our collection is developed with certified occupational therapists — the specialists parents turn to when children need support with movement, coordination, and independence. We brought them into the design process from the start, using clinical insight to engineer the weight, curve, and grip of every utensil to follow the true trajectory of a child's hand development.\n\nThe result is tableware that works with your child's body, not against it. Easier to hold. Easier to control. Designed to build confidence at the table, one meal at a time.\nOur work has been recognized by the Red Dot Award and iF Design Award — two of the most respected design institutions in the world — because we believe the tools children use every day deserve to be both exceptionally functional and genuinely beautiful.\n\nThis is premium tableware made for the most important hands in our life.",
    "brand.product1.name": "PICABOO DINING SET",
    "brand.product1.desc": "The way a child holds a spoon is also the way they'll one day hold a pencil. PICABOO is developed with certified occupational therapists to guide a correct, natural grip from the very first meal — making the transition to pencil-holding seamless, unhurried, and confident.\nClinically grounded — Every piece is co-developed with occupational therapists, engineered around the true trajectory of a child's hand development.\n\nSeamless transition — The grip logic of PICABOO flows directly into pencil-holding. Children build the right habits at the table before they ever enter a classroom.\n\nConfidence at every meal — When tools fit the hand, children pick up skills faster and want to do more on their own.\n\nAward-winning design — Recognized by the iF Design Award for design that is as beautiful as it is purposeful.",
    "brand.product2.name": "3 LITTLE BUDDY PLATE",
    "brand.product2.desc": "Good eating habits start with the right plate. BUDDY was developed with a certified nutritionist to build balanced portioning directly into the plate itself — so parents don't have to think about ratios, and children naturally learn what a balanced meal looks like.\n\nNutritionist-designed portions, effortless plating — The 2:1:1 division is nutritionist-calculated: grains, protein, and vegetables each in their place. No guesswork, every meal.\nModular design that grows with your child — The divider fits inside the plate for smaller appetites, or clips to the outside to expand capacity as your child grows. One plate, years of use.\n\nMakes kids want to come to the table — BUDDY transforms into different animal characters, turning mealtime into something children look forward to. Less convincing. More eating.\n2026 Red Dot Design Award Winner"
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "孩子大約在一歲左右，第一次憑自己的力量握起湯匙——那個瞬間，有件重要的事已經悄悄開始了。手掌裡的小肌肉，正展開往後數年的日常練習。早在他們拿起鉛筆之前，餐桌就已經是精細動作發展的起點。",
    "brand.summary": "孩子大約在一歲左右，第一次憑自己的力量握起湯匙——那個瞬間，有件重要的事已經悄悄開始了。手掌裡的小肌肉，正展開往後數年的日常練習。早在他們拿起鉛筆之前，餐桌就已經是精細動作發展的起點。\n\nCYD TERRA，從那個瞬間出發。\n我們的每一件產品，都與專業職能治療師共同開發。他們是當孩子在動作協調、肌肉控制與生活自理上需要支持時，父母最信賴的專家。我們從設計最初就邀請他們加入，以臨床視角精算每一件餐具的重量、弧度與握感，讓設計完整依循孩子手部發育的真實軌跡。\n最終呈現的，是一套順應孩子身體的餐具。更容易握持，更容易控制。每一餐，都在幫孩子建立屬於自己的自信。\n\n我們的設計獲得 Red Dot 紅點獎與 iF 設計獎肯定——全球最具公信力的兩大設計機構。因為孩子每天使用的器具，應該兼具卓越的功能性與真正的美感。\n\n這是為我們生命中最重要的那雙小手，打造的頂級餐具。",
    "brand.product1.name": "PICABOO 布咔寶學習餐具",
    "brand.product1.desc": "設計願景\n\n孩子握起湯匙的那一刻，其實也是握筆的練習。PICABOO 從職能治療師的臨床視角出發，設計一套順應孩子手部發育的餐具，讓正確的握持習慣在餐桌上自然養成，無痛銜接日後的握筆姿勢。\n\n核心價值\n\n臨床為本 — 每一件產品與專業職能治療師共同開發，設計依循兒童手部肌肉與骨骼的真實發育軌跡。\n無縫銜接 — 從餐具到鉛筆，握持的邏輯一脈相承。PICABOO 讓孩子在最日常的進食時光裡，靜靜為未來的書寫做好準備。\n建立自信 — 當餐具真正順手，孩子更快上手、更願意自己來，每一餐都是小小的成就感。\n設計卓越 — 榮獲 iF Design Award 國際肯定，功能性與美感同樣不妥協。",
    "brand.product2.name": "3 LITTLE BUDDY 三隻小嘟成長餐盤",
    "brand.product2.desc": "設計願景\n\n好好吃飯，從一個盤子開始。BUDDY 與專業營養師合作，將均衡飲食的邏輯直接內建進餐盤的結構裡——讓父母不需要每餐研究比例，孩子也能在不知不覺中養成正確的飲食習慣。\n核心價值\n\n營養師的比例，父母的輕鬆 — 2:1:1 的分隔比例由營養師精算，主食、蛋白質、蔬菜各就各位，備餐直覺、不出錯。\n隨食量成長的模組設計 — 分隔盤可以放進餐盤內，也可以套在外側擴充容量。孩子食量小的時候用內側，胃口變大了往外擴——一個餐盤，陪孩子吃好幾年。\n讓孩子想坐上餐桌 — 餐盤可以變身不同動物造型，吃飯變成一件有趣的事。孩子期待上桌，父母少一點說服，多一點享受。\n榮獲 2026 Red Dot Design Award 肯定"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Het moment dat een kind voor het eerst zelf een lepel vasthoudt – rond de leeftijd van één jaar – gebeurt er al iets belangrijks. De kleine spieren in hun hand beginnen aan jaren van rustige, dagelijkse oefening. Lang voo",
    "brand.summary": "Het moment dat een kind voor het eerst zelf een lepel vasthoudt – rond de leeftijd van één jaar – gebeurt er al iets belangrijks. De kleine spieren in hun hand beginnen aan jaren van rustige, dagelijkse oefening. Lang voordat ze ooit een potlood oppakken, is de eettafel de plek waar de ontwikkeling van de fijne motoriek begint.\n\nRond dat moment hebben we CYD TERRA gebouwd.\nElk stuk in onze collectie is ontwikkeld met gecertificeerde ergotherapeuten – de specialisten waar ouders zich toe wenden wanneer kinderen ondersteuning nodig hebben bij beweging, coördinatie en zelfstandigheid. We hebben hen vanaf het begin bij het ontwerpproces betrokken, en klinisch inzicht gebruikt om het gewicht, de kromming en de grip van elk eetgerei zo te ontwerpen dat het de ware ontwikkelingstraject van de kinderhand volgt.\n\nHet resultaat is kinderservies dat mét het lichaam van uw kind werkt, niet ertegenin. Makkelijker vast te houden. Makkelijker te controleren. Ontworpen om het zelfvertrouwen aan tafel te vergroten, maaltijd na maaltijd.\nOns werk is erkend door de Red Dot Award en de iF Design Award – twee van de meest gerespecteerde ontwerpinstituten ter wereld – omdat wij geloven dat de hulpmiddelen die kinderen dagelijks gebruiken zowel uitzonderlijk functioneel als oprecht mooi moeten zijn.\n\nDit is premium kinderservies, gemaakt voor de belangrijkste handjes in ons leven.",
    "brand.product1.name": "PICABOO EETSET",
    "brand.product1.desc": "De manier waarop een kind een lepel vasthoudt, is ook de manier waarop het op een dag een potlood zal vasthouden. PICABOO is ontwikkeld met gecertificeerde ergotherapeuten om een juiste, natuurlijke grip te begeleiden vanaf de allereerste maaltijd – waardoor de overgang naar het vasthouden van een potlood naadloos, ongedwongen en vol vertrouwen verloopt.\nKlinisch onderbouwd — Elk stuk is mede ontwikkeld met ergotherapeuten, ontworpen rond het ware ontwikkelingstraject van de kinderhand.\n\nNaadloze overgang — De greeplogica van PICABOO vloeit direct over in het vasthouden van een potlood. Kinderen ontwikkelen de juiste gewoontes aan tafel nog voordat ze de klas in gaan.\n\nZelfvertrouwen bij elke maaltijd — Wanneer hulpmiddelen goed in de hand liggen, leren kinderen sneller vaardigheden en willen ze meer zelf doen.\n\nBekroond design — Erkend door de iF Design Award voor een ontwerp dat even mooi als doelgericht is.",
    "brand.product2.name": "3 LITTLE BUDDY BORD",
    "brand.product2.desc": "Goede eetgewoontes beginnen met het juiste bord. BUDDY is ontwikkeld met een gecertificeerde voedingsdeskundige om een gebalanceerde portionering direct in het bord zelf te integreren – zodat ouders niet hoeven na te denken over verhoudingen, en kinderen op natuurlijke wijze leren hoe een gebalanceerde maaltijd eruitziet.\n\nDoor voedingsdeskundige ontworpen porties, moeiteloos opscheppen — De 2:1:1 verdeling is berekend door voedingsdeskundigen: granen, eiwitten en groenten elk op hun plek. Geen gokwerk, elke maaltijd.\nModulair ontwerp dat met uw kind meegroeit — De verdeler past in het bord voor kleinere eters, of klikt aan de buitenkant om de capaciteit uit te breiden naarmate uw kind groeit. Eén bord, jarenlang gebruik.\n\nMaakt dat kinderen graag aan tafel komen — BUDDY verandert in verschillende dierenfiguren, waardoor de maaltijd iets wordt waar kinderen naar uitkijken. Minder overtuigen. Meer eten.\nWinnaar van de Red Dot Design Award 2026"
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "お子さまが1歳頃に初めて自分でスプーンを握る瞬間 — そこにはすでに大切なことが起こっています。手の小さな筋肉は、静かで日々の練習を何年もかけて始めています。鉛筆を持つ",
    "brand.summary": "お子さまが1歳頃に初めて自分でスプーンを握る瞬間 — そこにはすでに大切なことが起こっています。手の小さな筋肉は、静かで日々の練習を何年もかけて始めています。鉛筆を持つずっと前から、食卓こそが微細運動能力の発達が始まる場所なのです。\n\n私たちはその瞬間に寄り添うCYD TERRAを開発しました。\n私たちのコレクションのすべてのピースは、認定作業療法士 — お子さまの動き、協調性、自立心にサポートが必要な時に親御さんが頼る専門家 — と共同で開発されています。私たちは彼らをデザインプロセスの最初期から巻き込み、臨床的知見を用いて、お子さまの手の発達の真の軌跡に沿うよう、各調理器具の重さ、曲線、握り方を設計しました。\n\nその結果、お子さまの体に逆らうのではなく、寄り添う食器が生まれました。持ちやすく、コントロールしやすい。一食ごとに食卓での自信を育むようにデザインされています。\n私たちの取り組みは、レッド・ドット・アワードとiFデザイン賞 — 世界で最も権威あるデザイン機関 — に認められました。それは、お子さまが毎日使う道具は、卓越した機能性と真の美しさを兼ね備えているべきだと私たちが信じているからです。\n\nこれは、私たちの人生で最も大切な手のために作られたプレミアムな食器です。",
    "brand.product1.name": "PICABOO DINING SET",
    "brand.product1.desc": "お子さまがスプーンを持つその持ち方は、いずれ鉛筆を持つようになる持ち方でもあります。PICABOOは、認定作業療法士と共同開発され、初めての食事から正しく自然な握り方を導き、鉛筆持ちへの移行をスムーズに、焦らず、自信を持って行えるようにします。\n臨床的根拠に基づいた設計 — すべてのピースは作業療法士と共同開発され、お子さまの手の発達の真の軌跡に基づいて設計されています。\n\nスムーズな移行 — PICABOOの握り方のロジックは、鉛筆持ちへと直接つながります。お子さまは教室に入る前から、食卓で正しい習慣を身につけます。\n\n食事ごとの自信 — 道具が手にフィットすると、お子さまはより早くスキルを習得し、自分でやりたがるようになります。\n\n受賞歴のあるデザイン — 用途と同じくらい美しいデザインとして、iFデザイン賞に認められました。",
    "brand.product2.name": "3 LITTLE BUDDY PLATE",
    "brand.product2.desc": "良い食習慣は、正しいお皿から始まります。BUDDYは、認定栄養士と共同開発され、バランスの取れた分量を皿自体に組み込むことで、親御さんが割合を考える必要がなく、お子さまは自然とバランスの取れた食事がどのようなものかを学びます。\n\n栄養士が設計した分量、簡単な盛り付け — 2:1:1の区分は栄養士によって計算されており、穀物、タンパク質、野菜がそれぞれ指定された場所に収まります。毎食、迷うことなく。\nお子さまの成長に合わせて変化するモジュラーデザイン — 仕切りは食欲の小さい時期には皿の内側にフィットし、お子さまの成長に合わせて容量を広げるために外側に取り付けることもできます。一枚のお皿で何年も使えます。\n\nお子さまが食卓に来たがるように — BUDDYは様々な​​動物キャラクターに変身し、食事の時間を子供たちが楽しみにするものに変えます。説得が減り、食事が増えます。\n2026年 レッド・ドット・デザイン賞 受賞"
  }
};

const allBrands = [
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "../../assets/srmark_image/優織隆_鳳梨葉纖維跳色托特包_1- Kelly Tseng.jpg" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "../../assets/srmark_image/ei studio-plant pot-01 - ei studio.png" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "../../assets/srmark_image/DSCF1948 - 元泰工坊.jpg" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "../../assets/srmark_image/賽先生科學工廠-After School - 人體血管分布刺繡套組-01 - Mr. Sci Science Factory.jpg" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "../../assets/srmark_image/有義器_渦輪濾杯_1 - Rhea Chou.jpg" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "../../assets/srmark_image/P1002357 - Gochi.jpg" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "../../assets/srmark_image/IMG_9086 - 角琉璃.JPG" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "../../assets/srmark_image/20240613 OTOP棒球椅_頁面_1 - liu Alvin (木酢達人 泰逸).jpg" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "../../assets/srmark_image/HEMEL-1 - li Iris.jpg" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w400" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w400" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w400" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
