// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Uffy was born in Taiwan, crafted with love by artisans with over 40 years of",
    "brand.summary": "Uffy was born in Taiwan, crafted with love by artisans with over 40 years of\n\nexperience. Together, we created the Acubrusher — a far-infrared scalp-\nmassaging brush that brings wellness into everyday life. Our first launch\n\ntouched many, with over 10,000 sold in just one year, raising 11 million\nNTD through the support of crowdfunding and our community.\n\nWhat many don’t see is that Taiwan is behind some of the world’s finest\nbrushes, often uncredited. We’re here to change that — to celebrate the\nhands behind each piece, and to share the beauty of mindful haircare with\nthe world.\n\nBecause at Uffy, we believe true care starts with you — from the root.",
    "brand.product1.name": "Uffy Acubrusher -Scalp Massage Hairbrush ",
    "brand.product1.desc": "Transforming the everyday act of brushing your hair into a key ritual for promoting circulation and enhancing overall well-being — this is the vision behind Uffy’s Far-Infrared Scalp Massage Brush.\n\nOver the course of three years, the team reimagined the ordinary “hairbrush” through dedicated design and research, collaborating with Taiwanese woodworking artisans to breathe new life into traditional craftsmanship. The result is a product created without compromise and without cutting corners: the Uffy Far-Infrared Scalp Massage Brush.\n\nCrafted with a hand-polished natural wooden handle and 24K gold-plated copper pins, every stroke delivers delicate, attentive care to the scalp, helping awaken the body’s natural circulation and supporting wellness from the roots.\n\nAt Uffy, we do not create products that are unnecessary or designed for rapid replacement. Enduring quality, made to last through years of use, together with thoughtful after-sales service, reflects our commitment to sustainability."
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "一把不計成本.不妥協的梳子 來自40年台灣製梳工藝 曾經的梳子製造大國，默默做日本、歐美品牌背後無名推手，而在台灣卻沒有能夠說得出口的品牌。因此，我們決心要打造一個屬於台灣的在地品牌，讓世界知道，這麼棒的產品是台灣製造！",
    "brand.summary": "一把不計成本.不妥協的梳子 來自40年台灣製梳工藝 曾經的梳子製造大國，默默做日本、歐美品牌背後無名推手，而在台灣卻沒有能夠說得出口的品牌。因此，我們決心要打造一個屬於台灣的在地品牌，讓世界知道，這麼棒的產品是台灣製造！",
    "brand.product1.name": "無非遠紅外線頭皮按摩梳",
    "brand.product1.desc": "讓最日常的梳頭，成為促進氣血循環，改善健康的關鍵，無非團隊將人手一把的『梳子』，透過三年時間的設計與專研，並與台灣木工職人合作，為傳統產業注入新血，打造不計成本，不妥協的：無非遠紅外線頭皮按摩梳\n使用手工打磨天然木柄與24K鍍金銅針，每一次梳理，都是對頭皮最無微不至的按摩照護，喚醒體內循環，讓健康從根本開始。\n不生產不被需要、快速淘汰的產品，經的起長久使用的品質與提供完善售後服務，更是無非對於永續的堅持。"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Uffy was born in Taiwan, crafted with love by artisans with over 40 years of",
    "brand.summary": "Uffy was born in Taiwan, crafted with love by artisans with over 40 years of\n\nexperience. Together, we created the Acubrusher — a far-infrared scalp-\nmassaging brush that brings wellness into everyday life. Our first launch\n\ntouched many, with over 10,000 sold in just one year, raising 11 million\nNTD through the support of crowdfunding and our community.\n\nWhat many don’t see is that Taiwan is behind some of the world’s finest\nbrushes, often uncredited. We’re here to change that — to celebrate the\nhands behind each piece, and to share the beauty of mindful haircare with\nthe world.\n\nBecause at Uffy, we believe true care starts with you — from the root.",
    "brand.product1.name": "Uffy Acubrusher -Scalp Massage Hairbrush ",
    "brand.product1.desc": "Transforming the everyday act of brushing your hair into a key ritual for promoting circulation and enhancing overall well-being — this is the vision behind Uffy’s Far-Infrared Scalp Massage Brush.\n\nOver the course of three years, the team reimagined the ordinary “hairbrush” through dedicated design and research, collaborating with Taiwanese woodworking artisans to breathe new life into traditional craftsmanship. The result is a product created without compromise and without cutting corners: the Uffy Far-Infrared Scalp Massage Brush.\n\nCrafted with a hand-polished natural wooden handle and 24K gold-plated copper pins, every stroke delivers delicate, attentive care to the scalp, helping awaken the body’s natural circulation and supporting wellness from the roots.\n\nAt Uffy, we do not create products that are unnecessary or designed for rapid replacement. Enduring quality, made to last through years of use, together with thoughtful after-sales service, reflects our commitment to sustainability."
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "Uffy was born in Taiwan, crafted with love by artisans with over 40 years of",
    "brand.summary": "Uffy was born in Taiwan, crafted with love by artisans with over 40 years of\n\nexperience. Together, we created the Acubrusher — a far-infrared scalp-\nmassaging brush that brings wellness into everyday life. Our first launch\n\ntouched many, with over 10,000 sold in just one year, raising 11 million\nNTD through the support of crowdfunding and our community.\n\nWhat many don’t see is that Taiwan is behind some of the world’s finest\nbrushes, often uncredited. We’re here to change that — to celebrate the\nhands behind each piece, and to share the beauty of mindful haircare with\nthe world.\n\nBecause at Uffy, we believe true care starts with you — from the root.",
    "brand.product1.name": "Uffy Acubrusher -Scalp Massage Hairbrush ",
    "brand.product1.desc": "Transforming the everyday act of brushing your hair into a key ritual for promoting circulation and enhancing overall well-being — this is the vision behind Uffy’s Far-Infrared Scalp Massage Brush.\n\nOver the course of three years, the team reimagined the ordinary “hairbrush” through dedicated design and research, collaborating with Taiwanese woodworking artisans to breathe new life into traditional craftsmanship. The result is a product created without compromise and without cutting corners: the Uffy Far-Infrared Scalp Massage Brush.\n\nCrafted with a hand-polished natural wooden handle and 24K gold-plated copper pins, every stroke delivers delicate, attentive care to the scalp, helping awaken the body’s natural circulation and supporting wellness from the roots.\n\nAt Uffy, we do not create products that are unnecessary or designed for rapid replacement. Enduring quality, made to last through years of use, together with thoughtful after-sales service, reflects our commitment to sustainability."
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "../../assets/srmark_image/PICABOO_01 - HAO I HSU.jpg" },
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "../../assets/srmark_image/優織隆_鳳梨葉纖維跳色托特包_1- Kelly Tseng.jpg" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "../../assets/srmark_image/ei studio-plant pot-01 - ei studio.png" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "../../assets/srmark_image/DSCF1948 - 元泰工坊.jpg" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "../../assets/srmark_image/賽先生科學工廠-After School - 人體血管分布刺繡套組-01 - Mr. Sci Science Factory.jpg" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "../../assets/srmark_image/有義器_渦輪濾杯_1 - Rhea Chou.jpg" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "../../assets/srmark_image/P1002357 - Gochi.jpg" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "../../assets/srmark_image/IMG_9086 - 角琉璃.JPG" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "../../assets/srmark_image/20240613 OTOP棒球椅_頁面_1 - liu Alvin (木酢達人 泰逸).jpg" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "../../assets/srmark_image/HEMEL-1 - li Iris.jpg" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w400" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w400" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w400" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w400" },
  { name: "EVOPURE+ 優織隆企業股份有限公司", category: "SR MARK Brand", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w400" },
  { name: "ei studio", category: "SR MARK Brand", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w400" },
  { name: "Yuantai 元泰竹藝社", category: "SR MARK Brand", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w400" },
  { name: "Mr.Sci Science Factory 賽先生科學工廠", category: "SR MARK Brand", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w400" },
  { name: "GUTS STUDIO 有義器", category: "SR MARK Brand", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w400" },
  { name: "ECOJOY", category: "SR MARK Brand", folder: "7-ECOJOY", image: "https://drive.google.com/thumbnail?id=1fu8za9qt7vSoVVp2eGyy3X6SGssJdNyW&sz=w400" },
  { name: "JIAO 角琉璃", category: "SR MARK Brand", folder: "8-JIAO", image: "https://drive.google.com/thumbnail?id=1JSh9469-8TcrtswUQCt8lOnkcEpgiyrR&sz=w400" },
  { name: "REWOOD Forest Cycle REWOOD森林循環", category: "SR MARK Brand", folder: "9-REWOOD", image: "https://drive.google.com/thumbnail?id=1lNf4a32YEWEf-X1HMMoUDBU06w1yr4pR&sz=w400" },
  { name: "HongJi Box Art Co., Ltd 宏吉盒藝有限公司", category: "SR MARK Brand", folder: "10-HONGJI", image: "https://drive.google.com/thumbnail?id=1J9nMzczqJ0qBV6YhNthCuxbEyN66pmPF&sz=w400" },
  { name: "Double Dribble 二次運球", category: "SR MARK Brand", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w400" },
  { name: "Simbalion 雄獅文具", category: "SR MARK Brand", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w400" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "SR MARK Brand", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w400" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
