// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Yuan Tai is based in Bamboo Hill/Zhushan, a township surrounded by the northern ranges of Alishan.",
    "brand.summary": "Yuan Tai is based in Bamboo Hill/Zhushan, a township surrounded by the northern ranges of Alishan.\nEstablished almost 40 years ago, Yuantai has gone through its golden era. However, the bamboo\nindustry is now perceived as a sunset industry. Bamboo needles, chopsticks, and crafts that Yuan Tai\nused to manufacture and export were replaced by cheaper plastics.\nWhen OA Lin, Yuan Tai' s second generation owner, went home to take over the small factory of 150\nsquare meters, he realised that there must be a total transformation to let bamboo re-enter our daily life.\nYuan Tai now aims to achieve sustainability by running a zero-waste factory.\nWe hope to let everyone live eco-friendly and still feel good.\n",
    "brand.product1.name": "feelgoodbambootoothbrush",
    "brand.product1.desc": "In the modern age, where excessive land development and deforestation by humans have led to the depletion of natural resources, countries around the world are promoting the concepts of energy conservation, carbon reduction, and environmental protection. Bamboo forests possess many advantages, including easy cultivation, rapid growth, abundant yield, and ecological sustainability. Therefore, the utilization of bamboo materials is bound to receive increasing attention.\n\nTaiwan has long been a country rich in bamboo resources. With the rise of environmental awareness today, the development of “green craftsmanship” has become highly valued, and creating everyday products from bamboo materials has become a growing trend. Bamboo forests absorb carbon dioxide at a rate four times greater than forests of the same area, while releasing 35 percent more oxygen than ordinary forests. They can truly be regarded as natural air purifiers. As a result, environmentally friendly bamboo materials are being developed into greener products that are closer to daily life.\n\nBamboo toothbrushes are made from Moso bamboo that is over three years old, while the bristles are made from horsehair. During the manufacturing process, no sulfur dioxide or bleach is used, and the coating applied is natural and non-toxic. Therefore, the toothbrush is highly durable and can completely biodegrade naturally in the environment without causing pollution to the Earth. It is an environmentally friendly and sustainable product.\n\nTaiwan consumes more than 100 million plastic toothbrushes every year, causing extremely serious environmental pollution. It is hoped that bamboo products can once again become part of everyday life. This would not only help reduce carbon emissions, but also revitalize the bamboo industry in Zhushan, allowing this declining traditional industry to create new opportunities through innovative products."
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "位於阿里山山脈北部的竹山鎮，一群群山環繞的小鎮，創立30幾年來與台灣一起經歷大量輸出竹材與竹製品的輝煌，如今竹製品被視為夕陽產業，早期被代工外銷的竹棒針，竹筷子及竹製品逐漸被更低廉的塑膠製品取代。",
    "brand.summary": "位於阿里山山脈北部的竹山鎮，一群群山環繞的小鎮，創立30幾年來與台灣一起經歷大量輸出竹材與竹製品的輝煌，如今竹製品被視為夕陽產業，早期被代工外銷的竹棒針，竹筷子及竹製品逐漸被更低廉的塑膠製品取代。\n第二代負責人林家宏返鄉接手後， 50坪的工廠，開始思考轉型「讓竹子重新進入生活」重新思考，用最環保的素材”竹子”來發想，開發了台灣第一支竹製牙刷，讓消費者有塑膠之外，更天然的選擇。\n我們以循環經濟為目標，開發所有產品，以零廢棄為原則，希望透過竹子，改變大家的生活\n",
    "brand.product1.name": "元氣竹牙刷",
    "brand.product1.desc": "在人類濫墾濫伐以致大自然資源越來越少的現代，世界各國一致提倡節能減碳、愛護\n地球的環保觀念下，竹林具備了栽植容易、成長迅速、產量豐富、生態環保的優勢，竹材\n的利用勢必逐漸被大家所重視；臺灣本是一個竹材產量豐富的國家，在環保意識抬頭的今\n日，「綠工藝」的發展備受關注，以竹材研製生活產品是流行趨勢。竹林吸收二氧化碳的\n能力是同等面積樹林的四倍，而釋出氧氣是樹林的百分之三十五，可謂純天然的空氣清淨\n機，將環保材料開發出更貼近生活的綠色產品。竹牙刷是採用三年以上的孟宗竹，刷毛部\n分是採用馬毛，製作過程不使用二氧化硫、漂白水，又是使用天然無毒的塗漆，所以整支\n是很耐用，也可以在環境中完全的自然分解掉，又不會對地球造成汙染，是相當環保且永\n續的友善產品，台灣每年消耗掉一億多支的塑膠牙刷，對環境的污染是非 常嚴重的，希望推動竹藝產品回歸生活日常用品，不但可以減少碳排放，也可以振興竹山 竹產業，由新興產品讓夕陽產業能開闢新的曙光"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "Yuan Tai is gevestigd in Bamboeheuvel/Zhushan, een gemeente omgeven door de noordelijke uitlopers van het Alishangebergte.",
    "brand.summary": "Yuan Tai is gevestigd in Bamboeheuvel/Zhushan, een gemeente omgeven door de noordelijke uitlopers van het Alishangebergte.\nBijna 40 jaar geleden opgericht, heeft Yuantai zijn gouden tijdperk meegemaakt. De bamboe-industrie wordt nu echter gezien als een zonsondergangindustrie. Bamboenaalden, eetstokjes en ambachten die Yuan Tai vroeger fabriceerde en exporteerde, zijn vervangen door goedkopere plastics.\nToen OA Lin, de tweede generatie eigenaar van Yuan Tai, naar huis terugkeerde om de kleine fabriek van 150 vierkante meter over te nemen, besefte hij dat er een totale transformatie nodig was om bamboe opnieuw deel uit te laten maken van ons dagelijks leven.\nYuan Tai streeft nu naar duurzaamheid door het runnen van een afvalvrije fabriek.\nWij hopen iedereen een milieuvriendelijk leven te laten leiden en zich nog steeds goed te laten voelen.",
    "brand.product1.name": "feelgoodbambootoothbrush",
    "brand.product1.desc": "In the modern age, where excessive land development and deforestation by humans have led to the depletion of natural resources, countries around the world are promoting the concepts of energy conservation, carbon reduction, and environmental protection. Bamboo forests possess many advantages, including easy cultivation, rapid growth, abundant yield, and ecological sustainability. Therefore, the utilization of bamboo materials is bound to receive increasing attention.\n\nTaiwan has long been a country rich in bamboo resources. With the rise of environmental awareness today, the development of “green craftsmanship” has become highly valued, and creating everyday products from bamboo materials has become a growing trend. Bamboo forests absorb carbon dioxide at a rate four times greater than forests of the same area, while releasing 35 percent more oxygen than ordinary forests. They can truly be regarded as natural air purifiers. As a result, environmentally friendly bamboo materials are being developed into greener products that are closer to daily life.\n\nBamboo toothbrushes are made from Moso bamboo that is over three years old, while the bristles are made from horsehair. During the manufacturing process, no sulfur dioxide or bleach is used, and the coating applied is natural and non-toxic. Therefore, the toothbrush is highly durable and can completely biodegrade naturally in the environment without causing pollution to the Earth. It is an environmentally friendly and sustainable product.\n\nTaiwan consumes more than 100 million plastic toothbrushes every year, causing extremely serious environmental pollution. It is hoped that bamboo products can once again become part of everyday life. This would not only help reduce carbon emissions, but also revitalize the bamboo industry in Zhushan, allowing this declining traditional industry to create new opportunities through innovative products."
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "Yuan Tai\u306f\u963f\u91cc\u5c71\u5c71\u8108\u5317\u90e8\u306e\u5c71\u3005\u306b\u56f2\u307e\u308c\u305f\u7af9\u5c71\u3092\u62e0\u70b9\u3068\u3057\u3066\u3044\u307e\u3059\u3002",
    "brand.summary": "Yuan Tai\u306f\u963f\u91cc\u5c71\u5c71\u8108\u5317\u90e8\u306e\u5c71\u3005\u306b\u56f2\u307e\u308c\u305f\u7af9\u5c71\u3092\u62e0\u70b9\u3068\u3057\u3066\u3044\u307e\u3059\u3002\n\u5275\u696d\u304b\u308240\u5e74\u4ee5\u4e0a\u3001Yuantai\u306f\u9ec4\u91d1\u6642\u4ee3\u3092\u7d4c\u9a13\u3057\u3066\u304d\u307e\u3057\u305f\u3002\u3057\u304b\u3057\u73fe\u5728\u3001\u7af9\u7523\u696d\u306f\u659c\u967d\u7523\u696d\u3068\u898b\u306a\u3055\u308c\u3066\u3044\u307e\u3059\u3002\u304b\u3064\u3066Yuan Tai\u304c\u88fd\u9020\u30fb\u8f38\u51fa\u3057\u3066\u3044\u305f\u7af9\u7de8\u307f\u91dd\u3001\u7b38\u3001\u7af9\u88fd\u54c1\u306f\u3001\u3088\u308a\u5b89\u4fa1\u306a\u30d7\u30e9\u30b9\u30c1\u30c3\u30af\u88fd\u54c1\u306b\u53d6\u3063\u3066\u4ee3\u308f\u3089\u308c\u307e\u3057\u305f\u3002\n\u4e8c\u4ee3\u76ee\u30aa\u30fc\u30ca\u30fcOA Lin\u304c150\u5e73\u65b9\u30e1\u30fc\u30c8\u30eb\u306e\u5c0f\u3055\u306a\u5de5\u5834\u3092\u5f15\u304d\u7d99\u3050\u305f\u3081\u306b\u5e30\u90f7\u3057\u305f\u6642\u3001\u7af9\u3092\u518d\u3073\u65e5\u5e38\u751f\u6d3b\u306b\u53d6\u308a\u623b\u3059\u305f\u3081\u306e\u5168\u9762\u7684\u306a\u5909\u9769\u304c\u5fc5\u8981\u3067\u3042\u308b\u3053\u3068\u3092\u609f\u308a\u307e\u3057\u305f\u3002\nYuan Tai\u306f\u73fe\u5728\u3001\u5ec3\u68c4\u7269\u30bc\u30ed\u306e\u5de5\u5834\u3092\u904b\u55b6\u3059\u308b\u3053\u3068\u3067\u6301\u7d9a\u53ef\u80fd\u6027\u3092\u8ffd\u6c42\u3057\u3066\u3044\u307e\u3059\u3002\n\u76686\u304c\u74b0\u5883\u306b\u512a\u3057\u3044\u751f\u6d3b\u3092\u9001\u308a\u306a\u304c\u3089\u3082\u3001\u5fc3\u5730\u3088\u3055\u3092\u611f\u3058\u3089\u308c\u308b\u3053\u3068\u3092\u9858\u3063\u3066\u3044\u307e\u3059\u3002",
    "brand.product1.name": "feelgoodbambootoothbrush",
    "brand.product1.desc": "In the modern age, where excessive land development and deforestation by humans have led to the depletion of natural resources, countries around the world are promoting the concepts of energy conservation, carbon reduction, and environmental protection. Bamboo forests possess many advantages, including easy cultivation, rapid growth, abundant yield, and ecological sustainability. Therefore, the utilization of bamboo materials is bound to receive increasing attention.\n\nTaiwan has long been a country rich in bamboo resources. With the rise of environmental awareness today, the development of “green craftsmanship” has become highly valued, and creating everyday products from bamboo materials has become a growing trend. Bamboo forests absorb carbon dioxide at a rate four times greater than forests of the same area, while releasing 35 percent more oxygen than ordinary forests. They can truly be regarded as natural air purifiers. As a result, environmentally friendly bamboo materials are being developed into greener products that are closer to daily life.\n\nBamboo toothbrushes are made from Moso bamboo that is over three years old, while the bristles are made from horsehair. During the manufacturing process, no sulfur dioxide or bleach is used, and the coating applied is natural and non-toxic. Therefore, the toothbrush is highly durable and can completely biodegrade naturally in the environment without causing pollution to the Earth. It is an environmentally friendly and sustainable product.\n\nTaiwan consumes more than 100 million plastic toothbrushes every year, causing extremely serious environmental pollution. It is hoped that bamboo products can once again become part of everyday life. This would not only help reduce carbon emissions, but also revitalize the bamboo industry in Zhushan, allowing this declining traditional industry to create new opportunities through innovative products."
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w1000" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "https://drive.google.com/thumbnail?id=1fu8za9qt7vSoVVp2eGyy3X6SGssJdNyW&sz=w1000" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "https://drive.google.com/thumbnail?id=1JSh9469-8TcrtswUQCt8lOnkcEpgiyrR&sz=w1000" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "https://drive.google.com/thumbnail?id=1lNf4a32YEWEf-X1HMMoUDBU06w1yr4pR&sz=w1000" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "https://drive.google.com/thumbnail?id=1J9nMzczqJ0qBV6YhNthCuxbEyN66pmPF&sz=w1000" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w1000" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w1000" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w1000" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+ 優織隆企業股份有限公司", category: "SR MARK Brand", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "ei studio", category: "SR MARK Brand", folder: "3-EI-STUDIO", image: "https://drive.google.com/thumbnail?id=1-dOXhQO_QC3Xd5MM-EkBYnZeG7wV9u3y&sz=w1000" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
