// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "EVOPURE+ is a sustainable fashion brand, focusing on providing eco-friendly textile products. Going from textile production to green production, EVOPURE+ sources locally as a commitment on reducing ca",
    "brand.summary": "EVOPURE+ is a sustainable fashion brand, focusing on providing eco-friendly textile products. Going from textile production to green production, EVOPURE+ sources locally as a commitment on reducing carbon footprints and energy waste. \nStarting from the perspective of sustainability, we incorporate the concept of environmentally friendly regeneration into our products by paying attention to daily life, and we don't neglect any details. The simple and clean design of our products can be matched according to personal preferences to create a style that is unique to you. Each product is a sign of our concern for environmental issues, and we are committed to reducing the carbon footprint of the apparel industry, and we will continue investing in the development and production of environmentally friendly materials, so that the beauty of the world can be sustained.\nMoreover, we also actively participate in various kind of cross-field collaborations to provide the public with more innovative, environmentally friendly and sustainable fibers, yarns and fabrics choices.",
    "brand.product1.name": "Pineapple leaf fiber tote bag",
    "brand.product1.desc": "EVOPURE+ transforms agricultural waste into eco-friendly fibers. This pineapple leaf fiber tote bag, winner of the 2025 MIT Taiwan Gold Selection, is not only a concrete practice of carbon reduction and environmental protection, but also our pursuit of sustainable living aesthetics. Through the combination of biodegradable technology and natural materials, we are committed to reducing carbon emissions, ensuring that every step we take lightly from the burden on the planet. By reshaping everyday accessories through \"recycling,\" we transform local Taiwanese agricultural waste into lightweight and durable lifestyle products.\nLet every consumption become a force for protecting the land, achieving a green fashion where aesthetics and ecology coexist."
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "EVOPURE+ 倡導永續時尚的理念，致力更多友善環境的紡織產品應用。品牌支持台灣在地的紡織原料，有效落實降低碳足跡。",
    "brand.summary": "EVOPURE+ 倡導永續時尚的理念，致力更多友善環境的紡織產品應用。品牌支持台灣在地的紡織原料，有效落實降低碳足跡。\n從永續出發，透過對日常的關注，將友善環境的再生理念融入產品本身，在細節上絲毫不輕忽，簡約俐落的商品設計，能依照個人喜好進行搭配，打造出專屬於自己的風格魅力。每一件商品都是我們對於環保議題的重視，致力降低服飾產業碳足跡，持續投入於環保材質開發與製作，讓世界的美好延續。\n我們同時也積極參與跨領域生態圈的合作，以期提供社會大眾更多創新環保且永續的纖維、紗線與布料選擇。",
    "brand.product1.name": "鳳梨葉纖維跳色托特包",
    "brand.product1.desc": "EVOPURE+ 將農業廢棄物轉化為環保纖維，這款榮獲 2025 MIT 台灣金選的鳳梨葉纖維托特包，不僅是減碳環保的具體實踐，更是我們對永續生活美學的追求。透過生物降解技術與天然材質的結合，我們致力於減少碳排放，讓每一步移動都能為地球減輕負擔。透過「循環再生」重塑日常配件，將台灣在地農廢轉化為輕巧耐用的生活良品。\n讓每一次消費都成為守護土地的力量，實現美感與生態共存的綠色時尚。"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "EVOPURE+ is een duurzaam modemerk, gericht op het aanbieden van milieuvriendelijke textielproducten. Van textielproductie naar groene productie, betrekt EVOPURE+ haar materialen lokaal als engagement om de CO2-voetafdruk en energieverspilling te verminderen.",
    "brand.summary": "EVOPURE+ is een duurzaam modemerk dat zich richt op het aanbieden van milieuvriendelijke textielproducten. Van textielproductie naar groene productie betrekt EVOPURE+ haar materialen lokaal, als engagement om de CO2-voetafdruk en energieverspilling te verminderen. \nVanuit een duurzaam perspectief integreren we het concept van milieuvriendelijke regeneratie in onze producten door aandacht te besteden aan het dagelijks leven, zonder ook maar enig detail te verwaarlozen. Het eenvoudige en strakke ontwerp van onze producten kan worden afgestemd op persoonlijke voorkeuren om een stijl te creëren die uniek is voor jou. Elk product is een teken van onze zorg voor milieukwesties, en we zetten ons in om de CO2-voetafdruk van de kledingindustrie te verminderen. We zullen blijven investeren in de ontwikkeling en productie van milieuvriendelijke materialen, zodat de schoonheid van de wereld behouden blijft.\nBovendien nemen we actief deel aan diverse cross-sectorale samenwerkingen om het publiek te voorzien van meer innovatieve, milieuvriendelijke en duurzame keuzes op het gebied van vezels, garens en stoffen.",
    "brand.product1.name": "Ananasbladvezel shopper",
    "brand.product1.desc": "EVOPURE+ transformeert agrarisch afval tot milieuvriendelijke vezels. Deze ananasbladvezel shopper, winnaar van de 2025 MIT Taiwan Gold Selection, is niet alleen een concrete praktijk van CO2-reductie en milieubescherming, maar ook onze zoektocht naar duurzame leefesthetiek. Door de combinatie van biologisch afbreekbare technologie en natuurlijke materialen zetten we ons in voor het verminderen van koolstofemissies, zodat elke stap die we zetten de belasting voor de planeet verlicht. Door alledaagse accessoires te hervormen via 'recycling', transformeren we lokaal Taiwanees agrarisch afval tot lichtgewicht en duurzame lifestyleproducten.\nLaat elke consumptie een kracht worden voor het beschermen van het land, en zo een groene mode realiseren waarin esthetiek en ecologie samenkomen."
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "EVOPURE+は、環境に優しいテキスタイル製品の提供に注力するサステナブルなファッションブランドです。テキスタイル生産からグリーン生産へと移行し、EVOPURE+はカーボンフットプリント削減へのコミットメントとして、地元での調達を行っています。",
    "brand.summary": "EVOPURE+は、環境に優しいテキスタイル製品の提供に注力するサステナブルなファッションブランドです。テキスタイル生産からグリーン生産へと移行し、EVOPURE+はカーボンフットプリントとエネルギーの無駄を削減するためのコミットメントとして、地元での調達を行っています。\nサステナビリティの視点から出発し、日常生活に目を向け、細部にまでこだわり、環境に優しい再生の概念を製品に取り入れています。シンプルでクリーンなデザインの製品は、個人の好みに合わせて、あなただけのスタイルを創造できます。各製品は環境問題への私たちの懸念の表れであり、アパレル業界のカーボンフットプリント削減にコミットしています。そして、世界の美しさが持続可能であるように、環境に優しい素材の開発と生産への投資を継続していきます。\nさらに、私たちは様々な分野を超えたコラボレーションにも積極的に参加し、一般の人々に、より革新的で、環境に優しく、持続可能な繊維、糸、生地の選択肢を提供しています。",
    "brand.product1.name": "パイナップルリーフ繊維トートバッグ",
    "brand.product1.desc": "EVOPURE+は農業廃棄物を環境に優しい繊維に変えます。このパイナップルリーフ繊維トートバッグは、2025年MIT台湾ゴールドセレクション受賞作品であり、カーボン削減と環境保護の具体的な実践であるだけでなく、サステナブルな生活美学の追求でもあります。生分解性技術と天然素材の組み合わせにより、私たちは炭素排出量削減にコミットし、地球への負担を軽くする一歩一歩を確実にしています。「リサイクル」を通じて日用品を再構築することで、台湾の地元の農業廃棄物を軽量で耐久性のあるライフスタイル製品へと変革しています。\nあらゆる消費を大地を守る力とし、美学とエコロジーが共存するグリーンファッションを実現しましょう。"
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "../../assets/srmark_image/PICABOO_01 - HAO I HSU.jpg" },
  { name: "ei studio", category: "Recycled Plastic / 再生塑膠", folder: "3-EI-STUDIO", image: "../../assets/srmark_image/ei studio-plant pot-01 - ei studio.png" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "../../assets/srmark_image/DSCF1948 - 元泰工坊.jpg" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "../../assets/srmark_image/賽先生科學工廠-After School - 人體血管分布刺繡套組-01 - Mr. Sci Science Factory.jpg" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "../../assets/srmark_image/有義器_渦輪濾杯_1 - Rhea Chou.jpg" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "../../assets/srmark_image/P1002357 - Gochi.jpg" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "../../assets/srmark_image/IMG_9086 - 角琉璃.JPG" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "../../assets/srmark_image/20240613 OTOP棒球椅_頁面_1 - liu Alvin (木酢達人 泰逸).jpg" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "../../assets/srmark_image/HEMEL-1 - li Iris.jpg" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w1000" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w1000" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w1000" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
