// Auto-generated by generate-brand-pages.js — edit freely

const translations = {
  en: {
    "nav.aboutReing": "About re-ing", "nav.sustainabilityCases": "Sustainability Cases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Contact Us",
    "common.home": "Home", "common.aboutBrand": "About the Brand", "common.aboutTitle": "About the Brand",
    "common.productsEyebrow": "Products", "common.productsTitle": "Design Works",
    "common.galleryEyebrow": "Gallery", "common.galleryTitle": "Photo Gallery",
    "common.otherBrandsEyebrow": "Explore More", "common.otherBrandsTitle": "Other Brands",
    "common.viewAllBrands": "View All Brands", "common.viewDetails": "View Details",
    "srmark.visitOfficial": "Visit Official Website",
    "footer.copyright": "© 2025 re-ing. All rights reserved.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "ei studio® specializes in upcycling regenerative materials, dedicated to exploring innovative design solutions. ",
    "brand.summary": "ei studio® specializes in upcycling regenerative materials, dedicated to exploring innovative design solutions. \n\nby leading the circular economy through thoughtful design, we conduct preliminary research into the unique characteristics of various materials, creating designs that extend their lifespan and add new value. our mission is to promote efficient resource utilization and environmental protection, driving the blueprint for a sustainable circular future.",
    "brand.product1.name": "MONO-ISM plant pot",
    "brand.product1.desc": "our mono-ism series flower pot is crafted from 60g of recycled single-use cutlery and takeaway food containers. made entirely from type 5 pp plastics collected across taiwan, reflecting our commitment to circularity. this pot transcends its function as a planter, embodying our circular design philosophy by transforming regenerative materials into something meaningful.",
    "brand.product2.name": "MONO-ISM comb",
    "brand.product2.desc": "our 100% recycled pp combs are crafted from 10g of recycled single-use plastics, combining functionality and sustainability in a compact design. inspired by the size of a standard business card, these combs fit perfectly in your pocket, making them easy to carry wherever you go. the neutral design caters to all users, while the harmonious color options, drawn from nature, and soft organic patterns created during the plastic extrusion process ensure each piece is truly one of a kind. a practical yet elegant accessory for on-the-go grooming.",
    "brand.product3.name": "MONO-ISM soap dish",
    "brand.product3.desc": "the soap dish is crafted from 60g of recycled single-use cutlery and takeaway food containers. made entirely from type 5 pp plastics collected across taiwan, it reflects our commitment to circularity. this dish transcends its function as a simple accessory, serving not only as a soap holder but also as a tray for jewelry, keys, or even as a base for crystals and diffusers, embodying our circular design philosophy by transforming regenerative materials into something purposeful."
  },
  zh: {
    "nav.aboutReing": "關於re-ing", "nav.sustainabilityCases": "永續設計案例",
    "nav.retwist": "RE:TWIST 轉圈圈計畫", "nav.srmark": "SR MARK 台灣永續設計聯盟", "nav.contact": "聯絡我們",
    "common.home": "首頁", "common.aboutBrand": "品牌介紹", "common.aboutTitle": "品牌介紹",
    "common.productsEyebrow": "產品作品", "common.productsTitle": "設計作品",
    "common.galleryEyebrow": "品牌影像", "common.galleryTitle": "品牌相簿",
    "common.otherBrandsEyebrow": "探索更多", "common.otherBrandsTitle": "其他品牌",
    "common.viewAllBrands": "查看所有品牌", "common.viewDetails": "查看詳情",
    "srmark.visitOfficial": "前往官方網站",
    "footer.copyright": "© 2025 re-ing. 保留所有權利。",
    "brand.category": "SR MARK 品牌",
    "brand.tagline": "ei studio® 專注於非原生材料的升級再造，致力探索創新設計解決方案。",
    "brand.summary": "ei studio® 專注於非原生材料的升級再造，致力探索創新設計解決方案。\n\n以設計引領循環經濟，藉由不同材料特性的前期研究，創作出延續材料生命並賦予其新價值的設計，以實現資源的有效利用和環境保護、推動循環未來的永續藍圖。",
    "brand.product1.name": "MONO-ISM 花盆",
    "brand.product1.desc": "花盆以 60 克的一次性餐具及外帶餐盒製成，採用在台灣回收的 5 號聚丙烯塑料，充分展現 ei studio 對循環永續的承諾。這款花盆不僅是一個栽植工具，更體現我們的循環設計理念，將再生材料轉化為富有意義的生活物品。",
    "brand.product2.name": "MONO-ISM 梳子",
    "brand.product2.desc": "100% 回收 PP 塑膠梳子由 10 克的一次性塑膠經回收後製成，將實用性與永續性融入精巧的設計中。啟發自名片的常見尺寸，這款梳子能輕鬆放入口袋、方便隨身攜帶。中性的設計適合所有使用者，而色彩靈感取自自然，加上塑膠擠壓過程中形成的自然有機紋路，讓每件作品獨具特色，展現簡約與優雅的生活美學。",
    "brand.product3.name": "MONO-ISM 肥皂架",
    "brand.product3.desc": "此款肥皂盤以 60 克回收的一次性餐具與外帶餐盒製成，採用台灣回收的 5 號聚丙烯塑料，展現對永續設計的承諾。不僅可作為肥皂托盤，還能靈活運用於日常生活，如收納飾品、鑰匙，或作為水晶與擴香器的底座。設計結合實用性與美感，以多元用途為居家空間注入循環再生的價值。"
  },
  nl: {
    "nav.aboutReing": "Over re-ing", "nav.sustainabilityCases": "Duurzaamheidscases",
    "nav.retwist": "RE:TWIST Project", "nav.srmark": "SR MARK Taiwan Sustainable Design Alliance", "nav.contact": "Neem Contact Op",
    "common.home": "Home", "common.aboutBrand": "Over het merk", "common.aboutTitle": "Over het merk",
    "common.productsEyebrow": "Producten", "common.productsTitle": "Ontwerpen",
    "common.galleryEyebrow": "Galerij", "common.galleryTitle": "Fotogalerij",
    "common.otherBrandsEyebrow": "Ontdek Meer", "common.otherBrandsTitle": "Andere Merken",
    "common.viewAllBrands": "Bekijk Alle Merken", "common.viewDetails": "Bekijk Details",
    "srmark.visitOfficial": "Officiële Website Bezoeken",
    "footer.copyright": "© 2025 re-ing. Alle rechten voorbehouden.",
    "brand.category": "SR MARK Brand",
    "brand.tagline": "ei studio\u00ae is gespecialiseerd in het upcyclen van geregenereerde materialen en is toegewijd aan het verkennen van innovatieve ontwerpoplossingen.",
    "brand.summary": "ei studio\u00ae is gespecialiseerd in het upcyclen van geregenereerde materialen en is toegewijd aan het verkennen van innovatieve ontwerpoplossingen.\n\nDoor de circulaire economie te leiden via doordacht ontwerp, voeren we vooronderzoek uit naar de unieke eigenschappen van materialen en creeren we ontwerpen die hun levensduur verlengen en nieuwe waarde toevoegen. Onze missie is het bevorderen van efficient gebruik van hulpbronnen en milieubescherming, als basis voor een duurzame circulaire toekomst.",
    "brand.product1.name": "MONO-ISM plant pot",
    "brand.product1.desc": "our mono-ism series flower pot is crafted from 60g of recycled single-use cutlery and takeaway food containers. made entirely from type 5 pp plastics collected across taiwan, reflecting our commitment to circularity. this pot transcends its function as a planter, embodying our circular design philosophy by transforming regenerative materials into something meaningful.",
    "brand.product2.name": "MONO-ISM comb",
    "brand.product2.desc": "our 100% recycled pp combs are crafted from 10g of recycled single-use plastics, combining functionality and sustainability in a compact design. inspired by the size of a standard business card, these combs fit perfectly in your pocket, making them easy to carry wherever you go. the neutral design caters to all users, while the harmonious color options, drawn from nature, and soft organic patterns created during the plastic extrusion process ensure each piece is truly one of a kind. a practical yet elegant accessory for on-the-go grooming.",
    "brand.product3.name": "MONO-ISM soap dish",
    "brand.product3.desc": "the soap dish is crafted from 60g of recycled single-use cutlery and takeaway food containers. made entirely from type 5 pp plastics collected across taiwan, it reflects our commitment to circularity. this dish transcends its function as a simple accessory, serving not only as a soap holder but also as a tray for jewelry, keys, or even as a base for crystals and diffusers, embodying our circular design philosophy by transforming regenerative materials into something purposeful."
  },
  ja: {
    "nav.aboutReing": "re-ingについて", "nav.sustainabilityCases": "サステナビリティケース",
    "nav.retwist": "RE:TWIST プロジェクト", "nav.srmark": "SR MARK 台湾サステナブルデザイン同盟", "nav.contact": "お問い合わせ",
    "common.home": "ホーム", "common.aboutBrand": "ブランドについて", "common.aboutTitle": "ブランドについて",
    "common.productsEyebrow": "製品", "common.productsTitle": "デザイン作品",
    "common.galleryEyebrow": "ギャラリー", "common.galleryTitle": "フォトギャラリー",
    "common.otherBrandsEyebrow": "もっと探す", "common.otherBrandsTitle": "他のブランド",
    "common.viewAllBrands": "すべてのブランドを見る", "common.viewDetails": "詳細を見る",
    "srmark.visitOfficial": "公式サイトを見る",
    "footer.copyright": "© 2025 re-ing. 全著作権所有。",
    "brand.category": "SR MARK ブランド",
    "brand.tagline": "ei studio\u00ae\u306f\u518d\u751f\u7d20\u6750\u306e\u30a2\u30c3\u30d7\u30b5\u30a4\u30af\u30eb\u3092\u5c02\u9580\u3068\u3057\u3001\u9769\u65b0\u7684\u306a\u30c7\u30b6\u30a4\u30f3\u30bd\u30ea\u30e5\u30fc\u30b7\u30e7\u30f3\u306e\u63a2\u6c42\u306b\u53d6\u308a\u7d44\u3093\u3067\u3044\u307e\u3059\u3002",
    "brand.summary": "ei studio\u00ae\u306f\u518d\u751f\u7d20\u6750\u306e\u30a2\u30c3\u30d7\u30b5\u30a4\u30af\u30eb\u3092\u5c02\u9580\u3068\u3057\u3001\u9769\u65b0\u7684\u306a\u30c7\u30b6\u30a4\u30f3\u30bd\u30ea\u30e5\u30fc\u30b7\u30e7\u30f3\u306e\u63a2\u6c42\u306b\u53d6\u308a\u7d44\u3093\u3067\u3044\u307e\u3059\u3002\n\n\u601d\u616e\u6df1\u3044\u30c7\u30b6\u30a4\u30f3\u3092\u901a\u3058\u3066\u5faa\u74b0\u7d4c\u6e08\u3092\u30ea\u30fc\u30c9\u3057\u3001\u3055\u307e\u3056\u307e\u306a\u7d20\u6750\u306e\u56fa\u6709\u306e\u7279\u6027\u3092\u4e8b\u524d\u306b\u8abf\u67fb\u3059\u308b\u3053\u3068\u3067\u3001\u305d\u306e\u5bff\u547d\u3092\u5ef6\u3070\u3057\u65b0\u305f\u306a\u4fa1\u5024\u3092\u52a0\u3048\u308b\u30c7\u30b6\u30a4\u30f3\u3092\u751f\u307f\u51fa\u3057\u3066\u3044\u307e\u3059\u3002\u79c1\u305f\u3061\u306e\u4f7f\u547d\u306f\u8cc7\u6e90\u306e\u52b9\u7387\u7684\u306a\u6d3b\u7528\u3068\u74b0\u5883\u4fdd\u8b77\u3092\u4fc3\u9032\u3057\u3001\u6301\u7d9a\u53ef\u80fd\u306a\u5faa\u74b0\u578b\u672a\u6765\u306e\u9752\u5199\u771f\u3092\u63cf\u304f\u3053\u3068\u3067\u3059\u3002",
    "brand.product1.name": "MONO-ISM plant pot",
    "brand.product1.desc": "our mono-ism series flower pot is crafted from 60g of recycled single-use cutlery and takeaway food containers. made entirely from type 5 pp plastics collected across taiwan, reflecting our commitment to circularity. this pot transcends its function as a planter, embodying our circular design philosophy by transforming regenerative materials into something meaningful.",
    "brand.product2.name": "MONO-ISM comb",
    "brand.product2.desc": "our 100% recycled pp combs are crafted from 10g of recycled single-use plastics, combining functionality and sustainability in a compact design. inspired by the size of a standard business card, these combs fit perfectly in your pocket, making them easy to carry wherever you go. the neutral design caters to all users, while the harmonious color options, drawn from nature, and soft organic patterns created during the plastic extrusion process ensure each piece is truly one of a kind. a practical yet elegant accessory for on-the-go grooming.",
    "brand.product3.name": "MONO-ISM soap dish",
    "brand.product3.desc": "the soap dish is crafted from 60g of recycled single-use cutlery and takeaway food containers. made entirely from type 5 pp plastics collected across taiwan, it reflects our commitment to circularity. this dish transcends its function as a simple accessory, serving not only as a soap holder but also as a tray for jewelry, keys, or even as a base for crystals and diffusers, embodying our circular design philosophy by transforming regenerative materials into something purposeful."
  }
};

const allBrands = [
  { name: "CYD TERRA", category: "Children's Living / 兒童生活設計", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+", category: "Sustainable Textile / 永續紡織", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" },
  { name: "元泰竹藝社 Yuantai", category: "Bamboo Products / 竹材日用品", folder: "4-YUANTAI", image: "https://drive.google.com/thumbnail?id=1zmPlomXad2v3VxfPdInFJnPVW05vAP7q&sz=w1000" },
  { name: "賽先生科學工廠", category: "Science & Lifestyle / 科學生活", folder: "5-MR-SCI", image: "https://drive.google.com/thumbnail?id=1KWGqiDcjmYs7HeYwcKR5dIrnLxYMfaCR&sz=w1000" },
  { name: "有義器 GUTS STUDIO", category: "Ceramic & Coffee / 陶瓷咖啡工藝", folder: "6-GUTS-STUDIO", image: "https://drive.google.com/thumbnail?id=1fnbCHlzc6zyoEk6xVCjBDMSyDQwhbLGt&sz=w1000" },
  { name: "ECOJOY", category: "Recycled Plastic / 再生塑膠家具", folder: "7-ECOJOY", image: "https://drive.google.com/thumbnail?id=1fu8za9qt7vSoVVp2eGyy3X6SGssJdNyW&sz=w1000" },
  { name: "角琉璃 JIAO", category: "Glass Craft / 玻璃文化工藝", folder: "8-JIAO", image: "https://drive.google.com/thumbnail?id=1JSh9469-8TcrtswUQCt8lOnkcEpgiyrR&sz=w1000" },
  { name: "REWOOD 森林循環", category: "Forest Circular Economy / 森林循環", folder: "9-REWOOD", image: "https://drive.google.com/thumbnail?id=1lNf4a32YEWEf-X1HMMoUDBU06w1yr4pR&sz=w1000" },
  { name: "HongJi Box Art 宏吉盒藝", category: "Sustainable Packaging / 永續包裝", folder: "10-HONGJI", image: "https://drive.google.com/thumbnail?id=1J9nMzczqJ0qBV6YhNthCuxbEyN66pmPF&sz=w1000" },
  { name: "Simbalion 雄獅文具", category: "Eco Art & Stationery / 永續美術文具", folder: "11-SIMBALION", image: "https://drive.google.com/thumbnail?id=1fvxSCFLbOUvvqmxTlAlAUiGZ8a8xnWpZ&sz=w1000" },
  { name: "Double Dribble 二次運球", category: "Sports Upcycling / 運動廢材升級再造", folder: "12-DOUBLE-DRIBBLE", image: "https://drive.google.com/thumbnail?id=1P9tnLB60T3IKiEytEsbqS5Gb2IZadB73&sz=w1000" },
  { name: "Courage Grocery 勇氣雜貨商行", category: "Eco Living / 永續生活選品", folder: "13-COURAGE-GROCERY", image: "https://drive.google.com/thumbnail?id=1D6DQwQQXDaTzkHdNq5h07rDeSoWlu9_8&sz=w1000" },
  { name: "CYD TERRA 項晴實業有限公司", category: "SR MARK Brand", folder: "1-CYD-TERRA", image: "https://drive.google.com/thumbnail?id=1BWHGRITvx-hKpT3W2r5VJnUJiffi7xGx&sz=w1000" },
  { name: "EVOPURE+ 優織隆企業股份有限公司", category: "SR MARK Brand", folder: "2-EVOPURE", image: "https://drive.google.com/thumbnail?id=1VTh6fQ-K6j5lPCsfUqT8Q6zVG1fyyRkC&sz=w1000" }
];

function switchLanguage(lang) {
  if (!translations[lang]) return false;
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key] !== undefined) el.innerHTML = translations[lang][key];
  });
  if (typeof generateRelatedBrands === 'function') generateRelatedBrands();
  localStorage.setItem('language', lang);
  const dd = bootstrap.Dropdown.getInstance(document.getElementById('langDropdown'));
  if (dd) dd.hide();
  return false;
}

function generateRelatedBrands() {
  const container = document.getElementById('related-brands-container');
  if (!container) return;
  if (!window._selectedBrands) {
    window._selectedBrands = allBrands.sort(() => 0.5 - Math.random()).slice(0, 3);
  }
  const lang = document.documentElement.getAttribute('data-lang') || 'en';
  const viewText = translations[lang]?.['common.viewDetails'] || 'View Details';
  container.innerHTML = window._selectedBrands.map((b, i) => `
    <div class="col-md-4" data-aos="fade-up" data-aos-delay="${i * 80}">
      <div class="brand-card">
        <div class="brand-card-img-wrap"><img src="${b.image}" alt="${b.name}" class="brand-card-img" loading="lazy"></div>
        <div class="brand-card-body">
          <div class="brand-card-category">${b.category}</div>
          <div class="brand-card-name">${b.name}</div>
          <a href="../${b.folder}/" class="view-more-btn">${viewText} <i class="fas fa-arrow-right"></i></a>
        </div>
      </div>
    </div>`).join('');
  AOS.refresh();
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('language') || 'en';
  if (saved !== 'en') switchLanguage(saved);
  generateRelatedBrands();
  AOS.init({ duration: 700, once: true, offset: 60 });
});
